### ISSUE TITLE
tegnine mtcnn手机运行出错

### ISSUE THREAD

**Issue by kuaikuaikim** [OAID/Tengine#100]
我调试到这步出错，大致是运行conv1这个operator出错，日志
Failed to execute on: conv1 Op: conv1

ACL是静态库链接的，config_acl_gpu=ON 手机是高通Adreno gpu，非mali gpu,不知道能否运行。

**Comment by cyberfire** [comment]
@kuaikuaikim 

It is probably due to the library cannot probe the correct CPU model. 
Maybe you can setup the device manually following the steps here:

https://github.com/OAID/Tengine/blob/master/doc/create_cpu_device.md

Thanks,

Haitao

**Comment by zjd1988** [comment]
HI @kuaikuaikim 
have you solved this problem？
