### ISSUE TITLE
lighten_cnn paper reference?

### ISSUE THREAD

**Issue by mrgloom** [OAID/Tengine#105]
Does `lighten_cnn` model have a paper reference?

**Comment by lyuchuny3** [comment]
Hi, here is the reference paper: 

[A Light CNN for Deep Face Representation with Noisy Labels](https://arxiv.org/abs/1511.02683) 

Thanks.

**Comment by xiang-zhe** [comment]
hi，i‘m not understand about the two file and i cann't open them：

data_16384 : the input data, 128x128 char

eltwise_fc1_256 : the data for comparing, 256 float

if i had a image（shape =（3，128，128）， how to convert it to data_16384-like， and eltwise_fc1_256 was a feature value of a face? and how to transform?

thank u very much
