### ISSUE TITLE
tengine_operations.c function image_permute 没看懂在干什么

### ISSUE THREAD

**Issue by huoshuai-dot** [OAID/Tengine#1051]
image image_permute(image src)
{
    float* GRB = ( float* )malloc(sizeof(float) * src.c * src.h * src.w);
    for (int c = 0; c < src.c; c++)
    {
        for (int h = 0; h < src.h; h++)
        {
            for (int w = 0; w < src.w; w++)
            {
                int newIndex = ( c )*src.h * src.w + h * src.w + w;
                int grbIndex = (2 - c) * src.h * src.w + h * src.w + w;
                GRB[grbIndex] = src.data[newIndex];
            }
        }
    }
    free(GRB);
    return src;
}
malloc了一块内存，一顿赋值 啥也没用就free掉了 这个函数是要做什么？rgb2bgr?
还有permute的作用是啥呢？

**Comment by cherryunix** [comment]
怕不是写反了
