### ISSUE TITLE
Does Tengine  support set thread count?

### ISSUE THREAD

**Issue by OceanWong1991** [OAID/Tengine#106]
Hi all,
   I know Tengine can bind cpu, but I can find any information about set thread count, Does Tengine support set thread count? THX!

**Comment by renfeier** [comment]
我看代码里好像是默认检测到有几个cpu，就会开几个线程？

**Comment by cyberfire** [comment]
@OceanWong1991 
by export TENGINE_CPU_LIST=0,1,2,3, you can control which CPUs are to be used.
