### ISSUE TITLE
Does img_h and img_w need to be equal at mssd.cpp?

### ISSUE THREAD

**Issue by vincent8877** [OAID/Tengine#107]
Hi team:

I have developed my own application following the coed [mssd.cpp](https://github.com/OAID/Tengine/blob/master/examples/mobilenet_ssd/mssd.cpp)

I trained a model based on mobilenet_ssd with model_height=200 and model_width=300, and when I tested this model with Tengine, I found that: 

if I set img_h=200, img_w=300, I just get a wrong output(can not detect anything or get wrong boxes), but when I set img_h=300,img_w=300(or img_h=200,img_w=200), I get a correct ouput, and it is unexpectedly that Tengine did not throw an error when img_h/img_w are not the same as model_height/model_weight.

Does Tengine need the img_h and img_w to be equal?

Anyone have experience with using Tengine to run a model which height/width are unequal?

**Comment by lyuchuny3** [comment]
Hi, mssd no need to set img_h == img_w, you can try by runing 
```
./build/test/bin/test_deploy mssd.prototxt mssd.caffemodel 240 320
```
it should be ok to run this mssd model with img_h!=img_w.

Thanks
