### ISSUE TITLE
windows上vs2019可以编译吗？

### ISSUE THREAD

**Issue by xinsuinizhuan** [OAID/Tengine#1071]

**Comment by xinsuinizhuan** [comment]
windows下面vs2019编译比较乱,使用camke进行编译，configure和generate都正常，但是
勾选了 tensorrt和cuda后，打开生成的sln进行编译，很多问题，C库链接错误，string不能识别

去掉tensorrt和cuda后，可以生成tengine-lite，没有生成tengine-lite.lib，只生成了tengine-lite.dll和tengine-lite_static.lib，但是demo什么的，去链接了tengine-lite.lib，demo改成了链接tengine-lite_static.lib，然后依然很多链接错误：
![图片](https://user-images.githubusercontent.com/40679769/130597009-dece4746-5daa-4395-9cd7-7cfae868f6d0.png)

**Comment by huoshuai-dot** [comment]
vs2019 只要安装Visual Studio Tools for CMake 你就直接打开文件夹 然后 配置下cmake选项 就直接可以编译 调试了 我这边就是这么做的 你可以试一下
