### ISSUE TITLE
quant_tool_uint8_perchannel 一些疑问

### ISSUE THREAD

**Issue by huoshuai-dot** [OAID/Tengine#1075]
1、常理来说 这个应该是quant-tool_uint8的一个特例，但是 为什么这个代码里面 conv的量化变成了int8的量化 并且 输入类型依然是uint8，这个后续inference怎么做的？还是说有一定的类型转换需要去做？

**Comment by BUG1989** [comment]
该模式是为了适配 TIM-VX 最新的量化策略，目前处于试验阶段。

**Comment by unsky** [comment]
有实验结论了吗
