### ISSUE TITLE
Tengine提供的protobuf库导致编译失败

### ISSUE THREAD

**Issue by dinghuanghao** [OAID/Tengine#108]
我使用的是v1.0.0 tag，protobuf库从https://github.com/OAID/Tengine/blob/master/doc/build_android.md 
指定的链接下载，错误如下：
================================
/Users/dinghuanghao/Project/tengine/serializer/include/te_caffe.pb.h:25:10: fatal error:
      'google/protobuf/generated_message_table_driven.h' file not found
#include <google/protobuf/generated_message_table_driven.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by hey-yahei** [comment]
Hi, dinghuanghao
Did you meet such an error when you build Tengine? There may be something wrong about your local protobuf. Look, pre-built protobuf library is built in c++_share for Android application. But when you build Tengine on ubuntu, local protobuf is necessary. 
So please run command `protoc --version` to check if you've installed protobuf on ubuntu and if the version is v3.0.0. 
If not, please follow [如何安装 protobuf 3.0.0？](https://github.com/OAID/Tengine/wiki/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85-protobuf-3.0.0%EF%BC%9F) to install protobuf3.0.0 before build Tengine.

Thanks
