### ISSUE TITLE
onnx模型转换失败

### ISSUE THREAD

**Issue by HAOCHENYE** [OAID/Tengine#1084]
[ttf_RepVGG_640_640.zip](https://github.com/OAID/Tengine/files/7063694/ttf_RepVGG_640_640.zip)

报错信息：
---- Tengine Convert Tool ---- 

Version     : v1.0, 18:54:45 Aug 26 2021
Status      : float32
Segmentation fault (core dumped)

之前转换过一次反卷积上采样的，结构相同的模型，是可以的。但是这个模型却不行，就很奇怪，我只用了卷积和resize

**Comment by FeiGeChuanShu** [comment]
请用Tengine-lite里的convert tool吧，别用那个convert tool的的git，刚试了下可以转换成功的。
---- Tengine Convert Tool ----

Version     : v1.0, 10:58:28 Aug 27 2021
Status      : float32

----------onnx2tengine begin----------
Model op set is :11
----------onnx2tengine done.----------
graph opt begin
graph opt done.
Convert model success. ./ttf_RepVGG_640_640.onnx -----> ./repvgg.tmfile

**Comment by yuxgis** [comment]
Tengine-lite里的convert tool 是如何编译的呢？cmake 编译显示报错信息如下：
FILE COPY cannot find
  "/home/host/Tengine/tengine-lite/tools/convert_tool/source/api/c_api.h".

**Comment by BUG1989** [comment]
@yuxgis 请参考 https://github.com/OAID/Tengine/blob/7b4cce6dd43ba2c2b7db9abced2ce0c63d9b14a2/.github/workflows/build-and-test.yml#L364
