### ISSUE TITLE
tim_vx clip  算子实现有问题

### ISSUE THREAD

**Issue by huoshuai-dot** [OAID/Tengine#1100]
clip 里面调用relu6 是个什么操作？
bool VXEngine::AddClipNode(struct node* ir_node)
{
    struct graph* ir_graph = ir_node->graph;

    struct tensor* input_tensor = get_ir_graph_tensor(ir_graph, ir_node->input_tensors[0]);
    struct tensor* output_tensor = get_ir_graph_tensor(ir_graph, ir_node->output_tensors[0]);

    auto relu = this->graph->CreateOperation<tim::vx::ops::Relu6>();
    (*relu).BindInput( this->vx_tensor_map[input_tensor->index] )
        .BindOutput({ this->vx_tensor_map[output_tensor->index] });

    return true;
}
这个relu6 应该不对吧

**Comment by BUG1989** [comment]
@BowShotDS
