### ISSUE TITLE
TIM-VX Depth2Space operator 出错 

### ISSUE THREAD

**Issue by huoshuai-dot** [OAID/Tengine#1105]
目前 Tengine模型中 depth2space算子没有mode设置 默认是CRD 但是TIM-VX默认的配置貌似是DCR 这样子的话 uint8的inference跟TIM-VX结果是对不上的

**Comment by FeiGeChuanShu** [comment]
可以加上，但可能会导致之前转的有depth2space的tmfile会不兼容

**Comment by GuideWsp** [comment]
转换工具是不是有问题呢？尝试将EDSR用tengine部署时发现，原本的DepthToSpace通过转换工具转换后的tmfile中变成了SpaceToDepth，进而导致graph运行报错。

**Comment by huoshuai-dot** [comment]
> 转换工具是不是有问题呢？尝试将EDSR用tengine部署时发现，原本的DepthToSpace通过转换工具转换后的tmfile中变成了SpaceToDepth，进而导致graph运行报错。

新版本已经修复了吧 你看看你的转换工具是不是最新的？
