### ISSUE TITLE
Android prebuilt packages baidu problem

### ISSUE THREAD

**Issue by NikolaMr** [OAID/Tengine#114]
Hi!

I have recently stumbled upon Tengine, tested it on a linux machine and wanted to give it a try on my android device also following the https://github.com/OAID/Tengine/blob/master/doc/build_android.md. However, I have a problem with the provided baidu link https://pan.baidu.com/s/1RPHK_ji0LlL3ztjUa893Yg. I can't download from that link without username and I'm from Europe which kinda complicates things. Could you somehow share prebuilt packages by some other hosting service?

Best regards,
Nikola

**Comment by lyuchuny3** [comment]
Hi, you can try this link: ftp://ftp.openailab.net.cn/Tengine_android_build/

**Comment by NikolaMr** [comment]
@lyuchuny3 Thanks for the link it is working :)
