### ISSUE TITLE
[Question]有没有 ssd检测模型检测精度测试的tool？

### ISSUE THREAD

**Issue by renfeier** [OAID/Tengine#116]
我看tools文件夹里面有测试yolov2的检测精度的sample，问一下有没有测试普通检测模型ssd系列的检测精度的sample呢 @mcharleb @Neo-Vincent @linyongye

**Comment by hey-yahei** [comment]
Hi, renfeier
I'm sorry that tools for ssd test are not provided yet. But I think you may imitate [tools/bin/test_yolov2.cpp](https://github.com/OAID/Tengine/blob/master/tools/bin/test_yolov2.cpp) to build it.

Thanks
