### ISSUE TITLE
build on linux, make error

### ISSUE THREAD

**Issue by dzyjjpy** [OAID/Tengine#117]
When I installed Tengine on Linux follow the guide:(https://github.com/OAID/Tengine/blob/master/doc/install.md)
when $ make -j8, it shows:
 **fatal errors:  arm_neon.h, no such file or directory.**
**I had upacked  Tengine_android_build, can find the arm_neon.h in android-ndk-r16b**
How should I solve the issue? where should I add the include path? in CMakeList.txt or makefile.config?
Thanks.

**Comment by hey-yahei** [comment]
Hi, dzyjjpy
Do you want to build Tengine for Android? If so, please follow the guide -- [build_android](https://github.com/OAID/Tengine/blob/master/doc/build_android.md).
Thanks

**Comment by dzyjjpy** [comment]
I want to build it on Linux at first, then on Android. Both linux and android tutorials, I tried to build, but failed. Now it shows:
**error:#error "Neon support not enabled"**

**Comment by hey-yahei** [comment]
Hi, dyzjjpy
Which platform do you want to build on? Neon is a part of arm-v8 processor.

If you want to build Tengine for x86, please install **openblas**, uncomment `CONFIG_ARCH_BLAS=y` and comment `CONFIG_ARCH_ARM64=y`.

If you want to build Tengine for arm(Linux) on x86, please follow [cross_compile](https://github.com/OAID/Tengine/blob/master/doc/cross_compile.md).

Thanks

**Comment by dzyjjpy** [comment]
Ubuntu 14.04 with all the packages download required in this tutorials.
https://github.com/OAID/Tengine/blob/master/doc/build_android.md

**Comment by dzyjjpy** [comment]
solved, caused by protocbuf, need to remove local pb clearly.

**Comment by erniuli** [comment]
@dzyjjpy 
你好，我碰到了和你类似的问题，首先按照linux build and Android build指导编译都正常通过了。
* 我想利用根目录下的CMakeList.txt自己构建，最终编译报executor/operator/common/lrn_arm.cpp:29:22: fatal error: arm_neon.h: No such file or directory
* 我的目的是想在x86下 用cmake构建，方便debug
* 目前，做了以下修改：根目录CMakeList.txt    option(CONFIG_ARCH_BLAS  "build blas  version" )OFF改为了ON，增加了set(PROTOBUF_DIR  ×× ）和add_subdirectory(examples) 
* 根据你的回答，PROTOBUF_DIR是需要设置为本地3.0.0的路径吗？
