### ISSUE TITLE
yolox inference too slow on Khadas VIM3

### ISSUE THREAD

**Issue by wdxybhb** [OAID/Tengine#1172]
Some one please help me.

I basically followed all the steps on https://zhuanlan.zhihu.com/p/392387835 to deploy YOLOX on VIM3.

1. Optimize yolox-s.onnx using "python3 yolov5s-opt.py --input yolox_s.onnx --output yolox_s_opt.onnx --in_tensor 503 --out_tensor output  "
2. convert onnx to tmfile via "./convert_tool/convert_tool -f onnx -m yolox_s_opt.onnx -o yolox_s_opt.tmfile"
3. Select 100 pics from coco and quantize model file via "./quantize/quant_tool_uint8 -m yolox_s_opt.tmfile -i quant/ -o yolox_s_uint8.tmfile -g 12,320,320 -w 0,0,0 -s 0.003921,0.003921,0.003921 -c 0 -k 1 -t 2 -y 640,640"
4. compile the Tengine on VIM3 following https://github.com/OAID/Tengine/blob/tengine-lite/doc/docs_zh/source_compile/compile_timvx.md, my Gal version is the latest 6.4.4_xxxAAA.

But when I run the tm_yolox_timvx I got the following printed messages:
./tm_yolox_timvx -m yolox_s_uint8.tmfile -i assets/test.png -r 1
tengine-lite library version: 1.4-dev
authorise ok
Repeat 1 times, thread 1, avg time 53321.20 ms, max_time 53321.20 ms, min_time 53321.20 ms
--------------------------------------
detection num: 0

Can someone please help me to figure out which section is going wrong?
I found the inference result is not correct as well.

Thank you so much for your help!

**Comment by liujiaxing7** [comment]
请问你是如何解决这个问题的
