### ISSUE TITLE
tengine在vim3上converttool的问题

### ISSUE THREAD

**Issue by lovehuanhuan** [OAID/Tengine#1173]
tengine model zoo的openpose_coco模型，在vim3上转化和量化，发现当指定输入图片尺寸不是正方形就会报错。
 ./quant_tool_uint8 -m openpose-caffe.tmfile -i images/ -o pose_uint83.tmfile -g 3,**640,640** -w 0,0,0 -s 0.0039,0.0039,0.0039 -z 1   这个方形量化，运行是没问题的
如果
 ./quant_tool_uint8 -m openpose-caffe.tmfile -i images/ -o pose_uint83.tmfile -g 3,**540,960** -w 0,0,0 -s 0.0039,0.0039,0.0039 -z 1  这个长方形量化，运行时就会报错
khadas@Khadas:~/etahAiTest/posedetect$ sudo ./tmpose -m pose_uint8.tmfile -i pose1.jpg 
tengine-lite library version: 1.5-dev
init tengind ok
create_graph ok
get_graph_input_tensor beg
set_tensor_shape beg
set_tensor_buffer beg
prerun_graph_multithread beg
E [op_check:333]Concat output dims size(68 vs 67)
E [setup_node:481]Check node[180] CONCAT fail
Tengine: Model compile to bin failed.Tengine Fatal: Pre-run subgraph(0) on TIMVX failed.
Tengine: Scheduler(sync) prerun failed.

链接：https://pan.baidu.com/s/13uk8NZ36cwOw6X43wtWpwg 
提取码：1234 
--来自百度网盘超级会员V5的分享

**Comment by huoshuai-dot** [comment]
同样的例子 convert tool在下x86 pc上没问题么？一般都不在vim3上进行转换量化的吧
