### ISSUE TITLE
Typos in comment / source

### ISSUE THREAD

**Issue by zchrissirhcz** [OAID/Tengine#1179]
Hi, Tengine Developers

There is `inital` which should be `initial` in Tengine source code:

![image](https://user-images.githubusercontent.com/3831847/137108368-ca0e313d-b7ae-4c24-9114-bfdc98e3c3e7.png)

It might be good to replace these typos. Thanks.

**Comment by cmdbug** [comment]
哈哈，zz大佬pr啊

**Comment by sxj731533730** [comment]
哈哈，zz大佬pr啊
