### ISSUE TITLE
ZYNQ7100编译报错

### ISSUE THREAD

**Issue by Wo-Ki** [OAID/Tengine#1194]
- uname -a:Linux arm 4.19.0-xilinx-v2019.1 #1 SMP PREEMPT Wed Oct 27 06:53:07 UTC 2021 armv7l armv7l armv7l GNU/Linux
- linux: 16.04
- gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12)
- cmake version :3.15.5

尝试在ZYNQ7100编译Tengine和Tengine lite，均出现一下错误：
![image](https://user-images.githubusercontent.com/29698317/139437517-0b153fce-7c6a-4f8c-9134-f4d4ae7779ce.png)
请问是什么问题？非常感谢

**Comment by tongjiaxuan666** [comment]
我遇到了同样的问题，请问是如何解决的呢

**Comment by Wo-Ki** [comment]
> 我遇到了同样的问题，请问是如何解决的呢

我这是mfpu问题，目前已经解决：

build/source/CMakeFiles/tengine-lite.dir/build.make 中，所有include后面加上：
ASM_FLAGS += -mfpu=neon

![image](https://user-images.githubusercontent.com/29698317/147933893-95ba47d9-d83f-45fe-8f2a-7af1c91ea498.png)

**Comment by tongjiaxuan666** [comment]
谢谢你的回复，我尝试一下

**Comment by tongjiaxuan666** [comment]
非常感谢，编译已经不报错了，我在zynq7000部署了nvdla,使用tengine推理框架，请问方便加一个QQ或者微信一起讨论嘛。

**Comment by Wo-Ki** [comment]
> 非常感谢，编译已经不报错了，我在zynq7000部署了nvdla,使用tengine推理框架，请问方便加一个QQ或者微信一起讨论嘛。

微信：XL1874421129
