### ISSUE TITLE
获取 Node 输出 Tensor api 疑问

### ISSUE THREAD

**Issue by aksenventwo** [OAID/Tengine#1195]
我在 `infer_ir_graph_shape` 函数中看到两种不同的取法，

取法 1：

https://github.com/OAID/Tengine/blob/5094dc52c846627c573489e199bcb85abe78c866/source/graph/graph.c#L232

取法 2：

https://github.com/OAID/Tengine/blob/5094dc52c846627c573489e199bcb85abe78c866/source/graph/graph.c#L266

请问这是特殊用意还是写错了？

**Comment by BUG1989** [comment]
一个是遍历的索引，一个是专门拿输出的。是一样的
