### ISSUE TITLE
ERROR: Compiler ' aarch64-linux-gnu-g++' not found

### ISSUE THREAD

**Issue by dzyjjpy** [OAID/Tengine#121]
When build ACL Driver, excute the command:
~/software/ComputeLibrary$ scons Werror=1 -j4 debug=0 asserts=1 neon=0 opencl=1 embed_kernels=1 os=linux arch=arm64-v8a

errors occured, does anyone know how to solve it?
scons: Reading SConscript files ...
ERROR: Compiler ' aarch64-linux-gnu-g++' not found

Any suggestions will be apprecited.

**Comment by hey-yahei** [comment]
Hi, dzyjjpy
It seams that you try to build ACL on x86 but without cross compiler. Please build it on your arm board or install cross compiler on x86 and then try again.
Thanks
