### ISSUE TITLE
模型加载时间太长

### ISSUE THREAD

**Issue by xiao-hua-sheng** [OAID/Tengine#1237]
nup推理，模型加载时间要30s，能不能减少加载时间了？

**Comment by wfeii1980** [comment]
yolov5s trt 加载要90s

**Comment by xiguadong** [comment]
> nup推理，模型加载时间要30s，能不能减少加载时间了？

cmake时设置 -DTENGINE_ENABLE_MODEL_CACHE=ON

**Comment by xiguadong** [comment]
这样只会在第一次加载时会花较长时间，

**Comment by xiao-hua-sheng** [comment]
> 这样只会在第一次加载时会花较长时间，



> > nup推理，模型加载时间要30s，能不能减少加载时间了？
> 
> cmake时设置 -DTENGINE_ENABLE_MODEL_CACHE=ON
请问是模型转换阶段，还是交叉编译生成example阶段了？不是很理解

**Comment by BUG1989** [comment]
> > 这样只会在第一次加载时会花较长时间，
> 
> > > nup推理，模型加载时间要30s，能不能减少加载时间了？
> > 
> > 
> > cmake时设置 -DTENGINE_ENABLE_MODEL_CACHE=ON
> > 请问是模型转换阶段，还是交叉编译生成example阶段了？不是很理解

编译 Tengine 源码时
