### ISSUE TITLE
Convert to model but  Loss some  op

### ISSUE THREAD

**Issue by qqqtankqqq** [OAID/Tengine#1238]
I  convert my onnx model to tmfile  by using Tengine-convert-tool  successfully. 
But tmfile loss some operation like relu and BatchNormalization(1d).

![netron1](https://user-images.githubusercontent.com/15229781/147071646-33a3da87-0837-499d-acde-71e5adf24a9c.png)
![netron2](https://user-images.githubusercontent.com/15229781/147071664-f3735a0b-8f2a-435b-97e4-b359eed52f5a.png)

I already try to  create just one BatchNormalization model. it works.

does anyone have similar problem?

**Comment by xiguadong** [comment]
convert-tool has optimized the model to decrease the caculate(the other forward frameworks also has this step). You could google bn-fold.

**Comment by BUG1989** [comment]
has been merged into convolution
