### ISSUE TITLE
tm_classification_timvx 在x86上模拟运行出问题

### ISSUE THREAD

**Issue by ywangwxd** [OAID/Tengine#1243]
在x86上编译出./tm_classification_timvx，依赖的库文件都有，但是测试运行总是报错 tengine-lite library version: 1.5-dev
Tengine: Size of tensor != size of buffer(618348 vs 154587). 这个size差4倍，是否是因为模型文件有要求？我是从benchmark
目录里的models目录随便选了几个。

**Comment by BUG1989** [comment]
需要使用 uint8 模型
