### ISSUE TITLE
ZYNQ7000 编译tengine lite报错

### ISSUE THREAD

**Issue by tongjiaxuan666** [OAID/Tengine#1248]
root@arm:~/Tengine/build# cmake .. -DTENGINE_ENABLE_OPENDLA=ON
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- TENGINE: 32Bit target OS is detected. Assume 32-bit compilation mode.
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test _is_hard_float_point
-- Performing Test _is_hard_float_point - Success
-- Found OpenMP_C: -fopenmp (found version "4.0")
-- Found OpenMP_CXX: -fopenmp (found version "4.0")
-- Found OpenMP: TRUE (found version "4.0")
-- Looking for pthread.h
-- Looking for pthread.h - found
--
--
-- Infomation Summary:
--
-- CMake infomation:
--   - CMake version:              3.22.1
--   - CMake generator:            Unix Makefiles
--   - CMake building tools:       /usr/bin/make
--   - Target System:              Linux
--   - Target CPU arch:            ARM
--   - Target building type:       release
--   - Target CPU bus width:       32 Bit
--
-- tengine-lite toolchain infomation:
--   Cross compiling: FALSE
--   C/C++ compilier:
--     - C   standard version:     C99
--     - C   standard required:    TRUE
--     - C   standard extensions:  ON
--     - C   compilier version:    5.4.0
--     - C   compilier:            /usr/bin/cc
--     - C++ standard version:     C++11
--     - C++ standard required:    TRUE
--     - C++ standard extensions:  OFF
--     - C++ compilier version:    5.4.0
--     - C++ compilier:            /usr/bin/c++
--   C/C++ compilier flags:
--     - C   compilier flags:
--     - C++ compilier flags:
--   OpenMP:
--     - OpenMP was found:         YES
--     - OpenMP version:           4.0
--
-- tengine-lite building infomation:
--   - Project source path is:     /root/Tengine
--   - Project building path is:   /root/Tengine/build
--
-- tengine-lite other infomation:
--   Package install path:         /root/Tengine/build/install
--
CMake Warning at cmake/summary.cmake:64 (MESSAGE):
    - Tengine Online Report is : ON
Call Stack (most recent call first):
  CMakeLists.txt:148 (INCLUDE)

-- Configuring done
-- Generating done
-- Build files have been written to: /root/Tengine/build
错误信息：
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S: Assembler messages:
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:107: Error: selected FPU does not support instruction -- `vmov.i64 d0,#0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:108: Error: selected FPU does not support instruction -- `vmov.i64 d1,#0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:109: Error: selected FPU does not support instruction -- `vmov.i64 d2,#0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:110: Error: selected FPU does not support instruction -- `vmov.i64 d3,#0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:111: Error: selected FPU does not support instruction -- `vmov.i64 d4,#0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:112: Error: selected FPU does not support instruction -- `vmov.i64 d5,#0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:114: Error: selected FPU does not support instruction -- `vmov.i64 d6,#0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:119: Error: selected processor does not support `vdup.s32 d1,r12' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:120: Error: selected processor does not support `vext.8 d0,d1,d6,#1' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:123: Error: selected processor does not support `vdup.s32 d3,r12' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:124: Error: selected processor does not support `vext.8 d2,d3,d6,#1' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:127: Error: selected processor does not support `vdup.s32 d5,r12' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:128: Error: selected processor does not support `vext.8 d4,d5,d6,#1' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:145: Error: selected processor does not support `vext.8 q9,q3,q3,#2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:146: Error: selected processor does not support `vext.8 q10,q4,q4,#2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:147: Error: selected processor does not support `vext.8 q11,q5,q5,#2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:148: Error: selected processor does not support `vmull.s8 q12,d6,d0' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:149: Error: selected processor does not support `vmull.s8 q13,d18,d0' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:150: Error: selected processor does not support `vmull.s8 q14,d6,d1' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:151: Error: selected processor does not support `vmull.s8 q15,d18,d1' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:153: Error: selected processor does not support `vmlal.s8 q12,d8,d2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:154: Error: selected processor does not support `vmlal.s8 q13,d20,d2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:155: Error: selected processor does not support `vmlal.s8 q14,d8,d3' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:156: Error: selected processor does not support `vmlal.s8 q15,d20,d3' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:157: Error: selected processor does not support `vpaddl.s16 q12,q12' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:158: Error: selected processor does not support `vpaddl.s16 q13,q13' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:159: Error: selected processor does not support `vpaddl.s16 q14,q14' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:160: Error: selected processor does not support `vpaddl.s16 q15,q15' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:162: Error: selected processor does not support `vmull.s8 q3,d10,d4' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:163: Error: selected processor does not support `vmull.s8 q4,d22,d4' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:164: Error: selected processor does not support `vmull.s8 q5,d10,d5' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:165: Error: selected processor does not support `vpadal.s16 q12,q3' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:166: Error: selected processor does not support `vmull.s8 q3,d22,d5' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:167: Error: selected processor does not support `vpadal.s16 q13,q4' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:168: Error: selected processor does not support `vpadal.s16 q14,q5' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:169: Error: selected processor does not support `vpadal.s16 q15,q3' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:171: Error: selected processor does not support `vpadd.s32 d24,d24,d25' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:172: Error: selected processor does not support `vpadd.s32 d25,d26,d27' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:173: Error: selected processor does not support `vpadd.s32 d28,d28,d29' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:174: Error: selected processor does not support `vpadd.s32 d29,d30,d31' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:176: Error: selected processor does not support `vtrn.32 q12,q14' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:178: Error: selected FPU does not support instruction -- `vmov.i64 d12,#0x0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:179: Error: selected FPU does not support instruction -- `vmov.s32 d13,d12'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:183: Error: selected processor does not support `vdup.s32 q6,r8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:186: Error: selected FPU does not support instruction -- `vadd.s32 q12,q12,q6'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:187: Error: selected FPU does not support instruction -- `vadd.s32 q14,q14,q6'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:190: Error: selected processor does not support `vdup.s32 q6,r7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:191: Error: selected processor does not support `vqrdmulh.s32 q12,q12,q6' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:192: Error: selected processor does not support `vqrdmulh.s32 q14,q14,q6' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:196: Error: selected processor does not support `vdup.s32 q6,r7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:198: Error: selected processor does not support `vdup.s32 q7,r7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:199: Error: selected processor does not support `vmax.s32 q8,q6,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:200: Error: selected processor does not support `vmin.s32 q7,q6,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:202: Error: selected processor does not support `vshl.s32 q12,q12,q8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:203: Error: selected processor does not support `vshl.s32 q14,q14,q8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:204: Error: selected processor does not support `vrshl.s32 q12,q12,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:205: Error: selected processor does not support `vrshl.s32 q14,q14,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:208: Error: selected processor does not support `vdup.s32 q7,r8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:210: Error: selected processor does not support `vdup.s32 q8,r8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:211: Error: selected processor does not support `vmax.s32 q12,q12,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:212: Error: selected processor does not support `vmax.s32 q14,q14,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:213: Error: selected processor does not support `vmin.s32 q12,q12,q8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:214: Error: selected processor does not support `vmin.s32 q14,q14,q8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:244: Error: selected processor does not support `vext.8 q9,q3,q3,#2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:245: Error: selected processor does not support `vext.8 q10,q4,q4,#2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:246: Error: selected processor does not support `vext.8 q11,q5,q5,#2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:247: Error: selected processor does not support `vmull.s8 q12,d6,d0' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:248: Error: selected processor does not support `vmull.s8 q13,d18,d0' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:249: Error: selected processor does not support `vmull.s8 q14,d6,d1' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:250: Error: selected processor does not support `vmull.s8 q15,d18,d1' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:252: Error: selected processor does not support `vmlal.s8 q12,d8,d2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:253: Error: selected processor does not support `vmlal.s8 q13,d20,d2' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:254: Error: selected processor does not support `vmlal.s8 q14,d8,d3' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:255: Error: selected processor does not support `vmlal.s8 q15,d20,d3' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:257: Error: selected processor does not support `vpaddl.s16 q12,q12' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:258: Error: selected processor does not support `vpaddl.s16 q13,q13' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:259: Error: selected processor does not support `vpaddl.s16 q14,q14' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:260: Error: selected processor does not support `vpaddl.s16 q15,q15' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:262: Error: selected processor does not support `vmull.s8 q3,d10,d4' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:263: Error: selected processor does not support `vmull.s8 q4,d22,d4' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:264: Error: selected processor does not support `vmull.s8 q5,d10,d5' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:265: Error: selected processor does not support `vpadal.s16 q12,q3' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:266: Error: selected processor does not support `vmull.s8 q3,d22,d5' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:267: Error: selected processor does not support `vpadal.s16 q13,q4' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:268: Error: selected processor does not support `vpadal.s16 q14,q5' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:269: Error: selected processor does not support `vpadal.s16 q15,q3' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:271: Error: selected processor does not support `vpadd.s32 d24,d24,d25' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:272: Error: selected processor does not support `vpadd.s32 d25,d26,d27' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:273: Error: selected processor does not support `vpadd.s32 d28,d28,d29' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:274: Error: selected processor does not support `vpadd.s32 d29,d30,d31' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:276: Error: selected processor does not support `vtrn.32 q12,q14' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:278: Error: selected FPU does not support instruction -- `vmov.i64 d12,#0x0'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:279: Error: selected FPU does not support instruction -- `vmov.s32 d13,d12'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:283: Error: selected processor does not support `vdup.s32 q6,r8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:286: Error: selected FPU does not support instruction -- `vadd.s32 q12,q12,q6'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:287: Error: selected FPU does not support instruction -- `vadd.s32 q14,q14,q6'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:290: Error: selected processor does not support `vdup.s32 q6,r7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:291: Error: selected processor does not support `vqrdmulh.s32 q12,q12,q6' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:292: Error: selected processor does not support `vqrdmulh.s32 q14,q14,q6' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:295: Error: selected processor does not support `vdup.s32 q6,r7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:297: Error: selected processor does not support `vdup.s32 q7,r7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:298: Error: selected processor does not support `vmax.s32 q8,q6,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:299: Error: selected processor does not support `vmin.s32 q7,q6,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:301: Error: selected processor does not support `vshl.s32 q12,q12,q8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:302: Error: selected processor does not support `vshl.s32 q14,q14,q8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:303: Error: selected processor does not support `vrshl.s32 q12,q12,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:304: Error: selected processor does not support `vrshl.s32 q14,q14,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:307: Error: selected processor does not support `vdup.s32 q7,r8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:309: Error: selected processor does not support `vdup.s32 q8,r8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:310: Error: selected processor does not support `vmax.s32 q12,q12,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:311: Error: selected processor does not support `vmax.s32 q14,q14,q7' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:312: Error: selected processor does not support `vmin.s32 q12,q12,q8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:313: Error: selected processor does not support `vmin.s32 q14,q14,q8' in ARM mode
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:326: Error: selected FPU does not support instruction -- `vmov.s32 q12,q14'
/root/Tengine/source/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S:330: Error: selected processor does not support `vext.8 q12,q12,q12,#4' in ARM mode
source/CMakeFiles/tengine-lite.dir/build.make:2496: recipe for target 'source/CMakeFiles/tengine-lite.dir/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S.o' failed
make[3]: *** [source/CMakeFiles/tengine-lite.dir/device/cpu/op/conv/cortex-a/armv7/dw_k3s1_int8.S.o] Error 1
CMakeFiles/Makefile2:365: recipe for target 'source/CMakeFiles/tengine-lite.dir/all' failed
make[2]: *** [source/CMakeFiles/tengine-lite.dir/all] Error 2
CMakeFiles/Makefile2:840: recipe for target 'examples/CMakeFiles/tm_classification_opendla.dir/rule' failed
make[1]: *** [examples/CMakeFiles/tm_classification_opendla.dir/rule] Error 2
Makefile:426: recipe for target 'tm_classification_opendla' failed
make: *** [tm_classification_opendla] Error 2

**Comment by BUG1989** [comment]
最后是通过删掉 source/device/cpu/op/conv/cortex-a 整个文件夹后，重新生成 cmake build 项目，重新编译即可。
