### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by TingfengTang** [OAID/Tengine#1266]
Hi ,the micro defined below will cause substitution error:
#define SET_LOG_PREFIX(prefix)                        \
    do                                                \
    {                                                 \
        struct logger* logger = get_default_logger(); \
        logger->prefix = prefix;                      \
    } while (0)

the code SET_LOG_PREFIX("myLogPrefix") will be expand to:

    do                                                \
    {                                                 \
        struct logger* logger = get_default_logger(); \
        logger->"myLogPrefix"= "myLogPrefix";                      \
    } while (0)

which is obviously wrong.

**Comment by RudyFoo** [comment]
I fix it via https://github.com/OAID/Tengine/pull/1268

**Comment by TingfengTang** [comment]
The fixed code may be covered by others,the latest code on github is still wrong.

**Comment by BUG1989** [comment]
@RudyFoo @TingfengTang #1268 has been merged.
