### ISSUE TITLE
最新的版本，支持CPU int8运算吗？如果支持，如何编译？

### ISSUE THREAD

**Issue by MomoDeLuo** [OAID/Tengine#127]
最新的版本，支持CPU int8运算吗？如果支持，如何编译？

**Comment by gaojinwei01** [comment]
Hi,

Tengine does support CPU int8 inference, but it's not open sourced.
Instead, we deliver prebuild library Tengine Explore for developers.
Contact me xiaowei@openailab.com if you need try the developer version.

Best regards,
Xiaowei
