### ISSUE TITLE
[Feature Request] some operators for convert_tool::tflite2tengine

### ISSUE THREAD

**Issue by fengwang** [OAID/Tengine#1273]
When I was converting a tflite model to tengine, I noticed there are [quite some operators are missing](https://github.com/OAID/Tengine/blob/tengine-lite/tools/convert_tool/tflite/tflite2tengine.cpp#L746)

- FULLY_CONNECTED
- REDUCE_MAX
- ELU
- ADD
- TRANSPOSE
- PAD

**Comment by BUG1989** [comment]
最新的模型转换工具 https://github.com/OAID/Tengine/tree/tengine-lite/tools/convert_tool/onnx 比较完整，请尝试将 tflite 的模型转换成 onnx。
