### ISSUE TITLE
How can I use TFLITE_SERIALIZER.

### ISSUE THREAD

**Issue by pighead1016** [OAID/Tengine#129]
There is not 'tf_lite' dir in 'serializer' dir.but the makefile like this 
ifeq ($(CONFIG_TFLITE_SERIALIZER),y)
    obj-y+=tf_lite/
    INC_DIR+=-I$(shell pwd)/include/tf_lite
    COMMON_CFLAGS+= -DCONFIG_TFLITE_SERIALIZER
endif

so .how can I build it

**Comment by cyberfire** [comment]
@pighead1016 
TFLITE Serializer is still under developing, so that it is not published in this version yet.

Thanks,

Haitao
