### ISSUE TITLE
[help wanted] which yolov5 implementation have you used to test convert_tool?

### ISSUE THREAD

**Issue by chenhu66** [OAID/Tengine#1291]
I picked an arbitrary yolov5 implementation online and converted it to onnx, Unfortunately, i got "segmentation fault" when using convert_tool. So i guess not any yolov5 would work out. Could you please share which one you used?

Error message:

./build/install/bin/convert_tool -f onnx -m models/1217.onnx -o models/1217.tmfile

---- Tengine Convert Tool ----

Version     : v1.0, 22:50:34 Feb 14 2022
Status      : float32

----------onnx2tengine begin----------
Model op set is: 13
Segmentation fault (core dumped)

**Comment by BUG1989** [comment]
please follow this https://zhuanlan.zhihu.com/p/360138163
