### ISSUE TITLE
yolov5s example failed 

### ISSUE THREAD

**Issue by chenhu66** [OAID/Tengine#1296]
I ran your example with the tmfile from your zoo, and got the following error:

./build/install/bin/tm_yolov5s -m models/yolov5s.tmfile  -i pics/ssd_dog_640.jpg
tengine-lite library version: 1.5-dev
Error: input elem num(408000) != reshaped elem num(102000)
Tengine FATAL: Infer node(id: 276, op: Reshape) shape failed.
Tengine: Infer shape of graph failed(-1).
Prerun multithread graph failed.

Coud you please help? Thank you.
![ssd_dog_640](https://user-images.githubusercontent.com/26198254/156943870-7fb6d90e-7782-4a67-ba17-a3ce46111e9f.jpg)

**Comment by chenhu66** [comment]
It worked out after changing #define YOLOV5_VERSION6 1 to #define YOLOV5_VERSION6 0

**Comment by Coder-TieHH** [comment]
Where is the "YOLOV5_VERSION6 1" code

**Comment by ccc120660** [comment]
同问，请问找到这代码在哪了吗
