### ISSUE TITLE
Tengine Convert Tool  not work with the least image！

### ISSUE THREAD

**Issue by 2050airobert** [OAID/Tengine#1311]
Hi，
Following the info of https://docs.khadas.com/linux/vim3/TengineSDK.html when I do this “./convert_tool -f darknet -m ~/yolov3.weights -p ~/yolov3.cfg -o yolov3.tmfile” then crash with the error info as below.

---- Tengine Convert Tool ----

Version : v1.0, 15:43:59 Jun 24 2021
Status : float32
Segmentation fault (core dumped)
My platform is ubuntu 20.04 server. Anything wrong ?

Could you please share the situable convert tool on my os ？ 
BR

**Comment by BUG1989** [comment]
Please compile the source code to get the latest version.

```
mkdir dir build
cd build
cmake -DTENGINE_BUILD_CONVERT_TOOL=ON ..
make
```
