### ISSUE TITLE
Deconvolution does not implement at arm platform?

### ISSUE THREAD

**Issue by renfeier** [OAID/Tengine#132]
i do not found the implementation of deconvoluiton layer at arm platform, it seems if i want run a model which has deconvoluiton layer, i must install cblas or other math comput library @linyongye @mcharleb

**Comment by lyuchuny3** [comment]
Hi,
Deconv implemented with Openblas library, which optimizes the gemm at arm platform. You can install openblas by `apt-get install libopenblas-dev`.

Thanks
