### ISSUE TITLE
when i crossing compliel tengle ,  make CROSS_COMPILE=aarch64-linux-gnu- ,errorr

### ISSUE THREAD

**Issue by maohuui** [OAID/Tengine#133]
graph_executor.cpp: In member function ‘TEngine::Graph* TEngine::GraphExecutor::GetOptimizedGraph()’:
graph_executor.cpp:571:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if(exec_handle_ == nullptr || exec_engine_ == nullptr)
     ^~
graph_executor.cpp:574:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  Graph* graph = exec_engine_->GetOptimizedGraph(exec_handle_)

**Comment by lyuchuny3** [comment]
Hi, 
The lastest commit in github should have solved this problem. Please pull the new codes and try it.
Thanks.
