### ISSUE TITLE
推理时间统计

### ISSUE THREAD

**Issue by TRQ-UP** [OAID/Tengine#1335]
请问tengine有做过每个模型 啥平台 性能多少的分析表格或者完档吗？
可以分享出来做宣传吗？

**Comment by cmdbug** [comment]
这个算？
[./benchmark/README.md](https://github.com/OAID/Tengine/blob/tengine-lite/benchmark/README.md)

**Comment by TRQ-UP** [comment]
> 这个算？ [./benchmark/README.md](https://github.com/OAID/Tengine/blob/tengine-lite/benchmark/README.md)

谢谢
