### ISSUE TITLE
onnx转tengine后，推理部分源码可使用的语言限制问题

### ISSUE THREAD

**Issue by luhuo** [OAID/Tengine#1349]
请问一下，如果我将onnx格式转tengine格式后部署到EAIDK上，后续推理部分源码的编写有语言的限制吗？C++和Python是否都可以使用？

**Comment by BUG1989** [comment]
目前能稳定使用的只有 C API

**Comment by luhuo** [comment]
> 目前能稳定使用的只有 C API

非常感谢您的回复！
