### ISSUE TITLE
init_tengine() 在rv1126板子上npu运行时初始化时间很久

### ISSUE THREAD

**Issue by blueskywwc** [OAID/Tengine#1364]
在板子上使用模型进行推理时速度很快，但j加载模型初始化时间很久，大概十几秒，能否有某种预编译模型的方式来把初始化速度降低到1秒以下呢，谢谢

**Comment by BUG1989** [comment]
CMake 构建工程时，请启用 TENGINE_ENABLE_MODEL_CACHE  功能 `-DTENGINE_ENABLE_MODEL_CACHE=ON`

**Comment by blueskywwc** [comment]
谢谢，但是我启用后没啥效果

cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabihf.toolchain.cmake -DTENGINE_ENABLE_MODEL_CACHE=ON -DTENGINE_ENABLE_TIM_VX=ON -DTENGINE_OPENMP=OFF ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /data/Tengine0407/rv1126/rv1126_rv1109_linux_sdk_v1.8.0_20210224/prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /data/Tengine0407/rv1126/rv1126_rv1109_linux_sdk_v1.8.0_20210224/prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /data/Tengine0407/rv1126/rv1126_rv1109_linux_sdk_v1.8.0_20210224/prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /data/Tengine0407/rv1126/rv1126_rv1109_linux_sdk_v1.8.0_20210224/prebuilts/gcc/linux-x86/arm/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
**CMake Warning:
  Manually-specified variables were not used by the project:

    TENGINE_ENABLE_MODEL_CACHE
    TENGINE_ENABLE_TIM_VX
    TENGINE_OPENMP**

为啥指定开启模型缓存没被使用呢，谢谢

-- Build files have been written to: /data/code_cross_compile/tengine_code/Tengine_palmvein/build

**Comment by blueskywwc** [comment]
你好，是我的问题描述不准确，实际是prerun_graph_multithread(graph, opt)执行起来很耗时间，大概23秒，有没有什么方式解决呢，谢谢！
