### ISSUE TITLE
TENGINE_ENABLE_MODEL_CACHE具体怎么使用呢

### ISSUE THREAD

**Issue by blueskywwc** [OAID/Tengine#1366]
prerun_graph_multithread很耗时间，TENGINE_ENABLE_MODEL_CACHE具体怎么使用来减少prerun的时间呢，有没有参考文档或demo，谢谢！

**Comment by BUG1989** [comment]
CMake 构建编译项目时，添加 `-DTENGINE_ENABLE_MODEL_CACHE = ON` 即可，第一次运行的时候会一样慢，第二次运行就会快很多，执行目录下会生成一个 cache file。
