### ISSUE TITLE
请教python中可以使用tengine吗？

### ISSUE THREAD

**Issue by shaozhenzhou** [OAID/Tengine#150]
请教如何在python中使用tengine，有人尝试过吗？

**Comment by cyberfire** [comment]
@shaozhenzhou 
It can be done by creating a python wrapper with tengine c api.  Current plan is to publish one in Q3.

Thanks,

Haitao

**Comment by shaozhenzhou** [comment]
谢谢！期待！

发自我的 iPhone

**Comment by yxandam** [comment]
@cyberfire 您好，我最近想通过tengine做目标检测，想python完成，您可以稍微详细的介绍一下怎么实现吗？感谢

**Comment by BUG1989** [comment]
@shaozhenzhou 在最新的版本中，已经支持了python api，请尝试，谢谢~

**Comment by shaozhenzhou** [comment]
谢谢！我我尝试一下！

发自我的iPhone
