### ISSUE TITLE
Where is the demo code of Multi-thread for CPU/GPU Heterogeneous scheduling Guide?

### ISSUE THREAD

**Issue by ysh329** [OAID/Tengine#157]
Hi, I found a guide named `Multi-thread for CPU/GPU Heterogeneous scheduling Guide` and found its fps is 23. I wanna ask where is the demo of of this CPU/GPU Heterogeneous scheduling Guide?

Thanks in advance.

**Comment by hey-yahei** [comment]
Hi, @ysh329 
The demo [tests/bin/mt_mssd.cpp](https://github.com/OAID/Tengine/blob/master/tests/bin/mt_mssd.cpp) may be helpful.

**Comment by ysh329** [comment]
Thanks 😆
