### ISSUE TITLE
error in testing resnet50 

### ISSUE THREAD

**Issue by ghimiredhikura** [OAID/Tengine#16]
I got following error while testing tengine resnet50 in my ubuntu machine. I kept default setting in etc/config file. Any idea please? 

./RESNET images/air.jpg ../../../models/resnet50/
Successfully load plugin : ../../build/operator/liboperator.so
OPERATOR PLUGIN INITED
Successfully load plugin : ../../build/serializer/libserializer.so
SERIALIZER PLUGIN INITED
Successfully load plugin : ../../build/executor/libexecutor.so
Register reference's operators
EXECUTOR PLUGIN INITED
Successfully load plugin : ../../build/driver/libdriver.so
DEV ENGINE PLUGIN INITED
Driver: RK3399 probed 5 devices
tensor: prob created by node: prob is not consumed
add the node: prob into output list
load resnet50 model done!
failed to set node ops for node: res2a op: Eltwise
graph_task.cpp:103 failed to Prerun task on  dev executor: cpu.rk3399.a72.all
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
graph_task.cpp:193 bad status: CREATED
Segmentation fault (core dumped)

**Comment by lyuchuny3** [comment]
I can run it successfully with default etc/config. Could you please verify your resnet50 model. You can find all the model files required by the examples in [https://pan.baidu.com/share/init?surl=LXZ8vOdyOo50IXS0CUPp8g](Tengine model zoo)
(psw: 57vb).

**Comment by ghimiredhikura** [comment]
well, thank you for your response. I will test with the models in tengine model zoo. 
I wanted to use tengine to test caffe SFD model for face detection. But It was uncessful. It gave same error. 
https://github.com/sfzhang15/SFD
I would love to hear your experience if you test above model. 
Thanks.

**Comment by lyuchuny3** [comment]
It seems that SFD is based on SSD. Tengine will release a new version to support ssd operators in these two weeks. You can try at that time.

**Comment by ghimiredhikura** [comment]
Yes SFD is based on SSD. That is great news, waiting to test SFD in Tengine. Thanks.

**Comment by ghimiredhikura** [comment]
I am trying to test ssd model. But I got problem in the first stage. any idea? 
compiled with AMD64 ubuntu 16.04 machine. 
```
./build/tests/bin/bench_sqz -r1
tensor: prob created by node: prob is not consumed
add the node: prob into output list
Load model successfully
failed to set node ops for node: conv1relu_conv1 op: Convolution
graph_task.cpp:225 failed to Prerun task on  dev executor: generic_probe
terminate called after throwing an instance of 'TEngine::bad_any_cast'
  what():  Bad any cast:  Expected: TEngine::MemPool*   Real: void
Aborted (core dumped)
```

**Comment by derek-zr** [comment]
@ghimiredhikura I also try SFD on tengine. The model was tranformed to tmfile successfully. But when i run it, i get the error: infer shaped for node: node_102 op: Eltwise failed. Have you test SFD on tengine successfully?
