### ISSUE TITLE
bench_sqz performance is poor in CortexA57

### ISSUE THREAD

**Issue by xiangchunyang** [OAID/Tengine#171]
performance of bench_sqz and bench_mobilenet is not excellent yet. 
platform: rk3399
Core: core4(1*A72)
frequency: 1.8GHz

experimental results:
bench_sqz: 88.3ms
bench_mobilenet:118.3ms

but in doc/benchmark.md, bench_sqz is 79.4, bench_mobilenet is  111.8ms

**Comment by liqi-c** [comment]
You can try to set cpu in performance  mode . if didn't solve you problem , please mail to Support@openailab.com or commit a new issue . thanks .
