### ISSUE TITLE
can't find quant_tm_model file

### ISSUE THREAD

**Issue by lostemples** [OAID/Tengine#172]
as  I make inistall, I didn't find quant_tm_model file. so is there anything wrong with the install

**Comment by lostemples** [comment]
my system is linux

**Comment by wentaoliupai** [comment]
me too

**Comment by hey-yahei** [comment]
Hi, @lostemples and @wentaoliupai 
I'm sorry that only Explorer version and Bussiness version support quantization, so `quant_tm_model` file is not included in github.

Thanks,
YaHei
