### ISSUE TITLE
how to run without protobuf?

### ISSUE THREAD

**Issue by cyf518** [OAID/Tengine#174]
How to transfer caffe model to tengine model, and compile it without protobuf?

**Comment by hey-yahei** [comment]
Hi, @cyf518 
Protobuf is required by caffe_serializer and tf_serializer. To compile a Tengine without dependency of protobuf, you can comment `CONFIG_CAFFE_SERIALIZER=y`, `CONFIG_TF_SERIALIZER=y`, `CONFIG_TFLITE_SERIALIZER=y` and uncomment `CONFIG_TENGINE_SERIALIZER=y` in [makefile.config](https://github.com/OAID/Tengine/blob/master/makefile.config.example) file. Then convert caffe model to tengine model with the [convert tool](https://github.com/OAID/Tengine/blob/master/tools/bin/convert_model_to_tm.cpp) (you would find it in `<TENGINE_DIR>/install/tool/` directory) and load tengine model in your application.

Thanks,
YaHei

**Comment by liqi-c** [comment]
You  can get convert tool from  release version : https://github.com/OAID/Tengine/releases . and then you didn't need compile without protobuf .
