### ISSUE TITLE
What is the difference between Tengine and Tensorflow Lite?

### ISSUE THREAD

**Issue by oujibahei** [OAID/Tengine#175]
1. Is Tengine the alternative/counterpart of Tensoflow Lite in arm/mobile platform?
2. Supposed that Jetson+Tensoflow could meet needs in most scenarios(besides cost), what is the purpose of Tengine solutions?

**Comment by erkaiyang** [comment]
Tensorflow Lite is a closed mode, which only supports tensorflow model. Other models need to be converted. Many customers have problems in the conversion process, while Tengine is an open mode, which supports Caffe, mxnet, Python and other models well. At the same time, Tengine has performance advantages and faster reasoning speed.
