### ISSUE TITLE
failed to convert mxnet model to tmfile

### ISSUE THREAD

**Issue by ThisisBillhe** [OAID/Tengine#178]
as concole indicated:
Parse the json file error in line 30000…46910,but there are not so many lines there.
Parse text file xxx.params failed
Create graph failed
errno:0

Besides, in function create_graph(nullptr, "mxnet", proto_file, model_file),it's said  get serializer failed, unknown model format "mxnet" . but i have modified the makefile.config to uncomment mxnet_serializer and make

**Comment by hey-yahei** [comment]
Hi, @ThisisBillhe 
* Please double check that you've provided correct  json file and param file. I think you may provide xxx.json and xxx.params as the fourth and the third parameter respectively for `create_graph` function. If so, swap them to solve such an issue.
* Maybe you've replaced `libtengine.so` with the explorer version which only support tengine format. If so, please convert your mxnet model to tengine model.

Thanks,
YaHei
