### ISSUE TITLE
YuFaceDetectNet run with gpu 

### ISSUE THREAD

**Issue by waveajay** [OAID/Tengine#181]
I added these lines to run with gpu in YuFaceDetectNe.cpp
`std::string device;
    device = "acl_opencl";
    set_graph_device(graph, device.c_str());`
It is compiling but while running i am getting an error
terminate called after throwing an instance of 'std::runtime_error'
  what():  in validate_arguments src/core/CL/kernels/CLCol2ImKernel.cpp:51: Objects have different dimensions
can anyone help me

**Comment by BUG1989** [comment]
We have updated the implement of ACL #540, please try is again, thanks.
