### ISSUE TITLE
Prerun graph failed, errno:0

### ISSUE THREAD

**Issue by ThisisBillhe** [OAID/Tengine#184]
The tm model was converted from a mxnet model.
"infer shaped for node:conv0_fwd_conv0_relu_fwd op:Convolution failed"
How to solve this problem?

**Comment by erkaiyang** [comment]
https://github.com/OAID/Tengine/wiki/%E6%94%AF%E6%8C%81%E7%9A%84OP
Tengine supports mxnet model. If it is not converted to TM model, can it run normally？

**Comment by bzhang5** [comment]
@ThisisBillhe First, check the input dims are correct or not, or the input dims are correct, then check the previous node or the next node of this issue node. You can print the dims info under node's infershape function, which can help you debug

Thanks
