### ISSUE TITLE
understanding "get_graph_output_tensor()" API.

### ISSUE THREAD

**Issue by rahulsharma11** [OAID/Tengine#195]
Hi,
While using Tengine, This(get_graph_output_tensor(graph, 0, 0)) API is used to get output_tensor and further is used to get floating values after Forward pass.
I have seen the second and third parameters are always 0 and denotes "output_node_idx" and "tensor_idx" respectively. 

Question-
Why these values are always 0,0. Should it be not the last node values of the model?

This issue comes in picture while using one of the mobilenet_ssd object detector (91 classes), While using same default values(0,0) there was not output but when i putted last node value such as "get_graph_output_tensor(graph, 10, 0))", Output was there.

Any suggestions?
Thanks.

**Comment by cyberfire** [comment]
@rahulsharma11 

the output_node_idx is the index of the node in the whole graph output node set.
You can call dump_graph(graph) to get the output node list.

Thanks,

Haitao
