### ISSUE TITLE
Can't download from Model ZOO

### ISSUE THREAD

**Issue by mhsattarian** [OAID/Tengine#197]
Hi,
models in model zoo are hosted on Baidu which asks for a Chinese number to create an account, can you please provide another way to download them?

**Comment by LEMON-LM** [comment]
ftp://ftp.openailab.net.cn/Tengine_models/

**Comment by lutzroeder** [comment]
@LEMON-LM The `tmfile` folder is empty?

Is it possible to move the model zoo to a location like GitHub that can be accessed using `curl` and HTTP requests without passwords?

**Comment by LEMON-LM** [comment]
> @LEMON-LM The `tmfile` folder is empty?
> 
> <img alt="screenshot" width="727" src="https://user-images.githubusercontent.com/438516/78852430-225f0600-79d1-11ea-8aad-04168b9e5781.png">
> 
> @BUG1989 Is it possible to move the model zoo to a location like GitHub that can be accessed using `curl` and HTTP requests without passwords?

You can get it from Google Drive now.
https://drive.google.com/open?id=1FE9Nz6EHHGZYZ1goYO5NcqiAWbLHRX0D

**Comment by pierricklee** [comment]
@LEMON-LM 
According to [Tengine/issue261](https://github.com/OAID/Tengine/issues/261), the tmfile format needs a fix, all model files have to be regenerated when we done. Please disable the access to Google Drive and reopen it after upload new model files. 

Cheers.

**Comment by LEMON-LM** [comment]
> @LEMON-LM
> According to [Tengine/issue261](https://github.com/OAID/Tengine/issues/261), the tmfile format needs a fix, all model files have to be regenerated when we done. Please disable the access to Google Drive and reopen it after upload new model files.
> 
> Cheers.

ok,I`ll close it now.
