### ISSUE TITLE
Why spend so long time(about 20 sec for each infer) to run example of "bench_sqz" in ARM chip with 4 A7 core. Is it normal ?

### ISSUE THREAD

**Issue by raygong1207** [OAID/Tengine#200]
# ./bench_sqz1 -p "0,1,2,3" -d "a7" -r 2
ENV SET: [0,1,2,3]
run-time library version: 1.9.0

Shared library not found: liba7.so: cannot open shared object file: No such file or directory

Device a7 cannot be found
liba7.so cannot be loaded either
REPEAT COUNT1= 2
Repeat [2] time 19444552.00 us per RUN. used 38889105 us
0.2831 - "n02123045 tabby, tabby cat"
0.2714 - "n02123159 tiger cat"
0.1687 - "n02119789 kit fox, Vulpes macrotis"
0.0843 - "n02124075 Egyptian cat"
0.0750 - "n02085620 Chihuahua"
--------------------------------------
ALL TEST DONE

**Comment by BUG1989** [comment]
Please try the latest version, thank you.
