### ISSUE TITLE
Add copyright notices to code copied from ncnn

### ISSUE THREAD

**Issue by nihui** [OAID/Tengine#204]
This repository contains (modified) copies of source code taken from other open source projects, with the copyright notices removed against the terms of the license. ncnn is BSD-3 licensed

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

You can refer how paddle-lite project does it

https://github.com/PaddlePaddle/Paddle-Lite/blob/321d4f9b0b1c96ee45a42920655e1ce87474678f/lite/core/device_info.cc
https://github.com/PaddlePaddle/Paddle-Lite/blob/18d974c04c96d9ba5ebd1b1101be14c8888e2a97/lite/utils/cv/image_resize.cc
https://github.com/PaddlePaddle/Paddle-Lite/blob/d1b7aec5a5bc2448c7975fba9e8ab86d6ee75f84/lite/backends/arm/math/interpolate.cc

**Comment by BUG1989** [comment]
Update the licence of  https://github.com/OAID/Tengine/blob/master/executor/operator/arm64/interp_float.cpp
