### ISSUE TITLE
compatibility with opencv mat

### ISSUE THREAD

**Issue by soham24** [OAID/Tengine#205]

**Comment by soham24** [comment]
I get buffer from camera feed, I read it as opencv mat and then rotate. 
I need to pass this in tengine Image format.
is there any compatibility?
I don't want to process extra copy operation.

**Comment by LEMON-LM** [comment]
Why you need change opencv Mat to tengine ImageFormat?

**Comment by LEMON-LM** [comment]
Why you need change Mat to tengine ImageFormat?
you can use the data of Mat to inference.
https://github.com/OAID/Tengine/blob/v1.3.2/examples/imagenet_classification/classification.cpp
you can refer to this example, how to use tengine with opencv.

**Comment by BUG1989** [comment]
@soham24 
we have update the example with OpenCV Mat format
https://github.com/OAID/Tengine/blob/master/examples/classification_cv.cpp

**Comment by soham24** [comment]
thanks
