### ISSUE TITLE
set "CONFIG_TF_SUPPORT=y" build error

### ISSUE THREAD

**Issue by wmorders** [OAID/Tengine#21]
build error : graph.pb.h not such file or path........
set "CONFIG_TF_SUPPORT=y" need install tensorflow first?

**Comment by cyberfire** [comment]
@wmorders 

It looks like that graph.pb.h is not generated during compiling and it needs protoc >=3.0 to  compile TF  proto files.

Could you please check if protoc is available in your system?

-Haitao

**Comment by wmorders** [comment]
i will upgrade protoc version to 3.6 to  build , thanks!
