### ISSUE TITLE
reshape operator 遇到-1 就出问题

### ISSUE THREAD

**Issue by azuredsky** [OAID/Tengine#210]
reshape operator 遇到-1 就出问题，纬度不对，这个bug 从1.9 就有

**Comment by BUG1989** [comment]
@azuredsky 这个是基于哪种框架模型转换过来的呢？有模型提供测试吗？谢谢

**Comment by azuredsky** [comment]
> @azuredsky 这个是基于哪种框架模型转换过来的呢？有模型提供测试吗？谢谢
https://github.com/cholihao/Retinaface-caffe/blob/master/caffemodel
https://github.com/cholihao/Retinaface-caffe/blob/master/caffemodel/mnet.prototxt

**Comment by BUG1989** [comment]
@azuredsky #212 Please try it again.

**Comment by azuredsky** [comment]
@BUG1989  ,good job ,it's ok now

**Comment by BUG1989** [comment]
@hey-yahei Thanks to you for your contribution
