### ISSUE TITLE
Is  Fp16 supported?

### ISSUE THREAD

**Issue by nopattern** [OAID/Tengine#22]
Thank you for your great job. Is Fp16 supported ? And the input data preprocess is slow in exmaples such as  get_input_data_ssd () in mobilenet_ssd . Has any plan to speed up? Thank you again.

**Comment by cyberfire** [comment]
@nopattern 

The work to support fp16 is still ongoing. 
Thank your suggestion to improve the performance of image pre-process, we will look into this.

-Haitao

**Comment by nopattern** [comment]
Thank you . 
  The image pre-process cost about 1-ms on my platform, so it 's may not big deal.

**Comment by vincent8877** [comment]
Thanks for your great work.
And please let me know if you have support FP16 inference.
