### ISSUE TITLE
[pytorch to onnx run in tengine error] ：Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero #49

### ISSUE THREAD

**Issue by fyq00** [OAID/Tengine#221]
Describe the bug
The bug is :
/home/ff/Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero

I trained my model with Pytorch and then transfered to onnx，using Ubuntu16.04.
When I use Tengine to run my model, bug appeared,like following:
These 3op are not supported
{shape, Gather, Unsqueeze}

Then I try onnx_simplifier,here is the new bug:
/home/ff/Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero

when I run API : dump_grap(grap);
It's following photo:
 
![144QP5KYC}PS4R1 ZKKH534](https://user-images.githubusercontent.com/50401350/77137877-a137e180-6aaa-11ea-93c2-b6b293ebbdf0.png)

I don't know how to solve this problem~

**Comment by BUG1989** [comment]
@fyq00  
We have fixed the bug in #226  , 
please try it again : )

**Comment by fyq00** [comment]
Thanks ! 
Now I can run my onnx model in Tengine.But the Model inference time becomes long！
Like the photo show：
I run the example of classification with mobilenetv2
![Uploading PS9W[0{W8N_7A4%FSR}NKO8.png…]()

It takes 5000ms!
and then I test mobienetssd

It takes 10000ms!

I change to the old version of Tengine and run the example of MobileNetSSD,
![MMMW2N3 FF $6Y4KVYXLCD](https://user-images.githubusercontent.com/50401350/77244102-8309e700-6c4c-11ea-981d-a54cf0046df4.png)
It only take 200ms~
My cpu seems too be fine~
Do you know whats problem about this?

#Ubuntu16.04 (with VMware)

**Comment by fyq00** [comment]
Thanks !&nbsp;
But&nbsp; I got some new problems, the inference time seems to longer than before~
https://github.com/OAID/Tengine/issues/221#issuecomment-602157187




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BUG1989"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 下午4:34
收件人: "OAID/Tengine"<Tengine@noreply.github.com&gt;; 
抄送: "nabob`男人"<229247822@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [OAID/Tengine] [pytorch to onnx run in tengine error] ：Tengine-master/core/lib/graph_executor.cpp:357 infer shape failed on node: 454 due to input: 453 size is zero #49 (#221)





 
Closed #221.

**Comment by BUG1989** [comment]
I have fixed the bug of x86 ops not register, #227 : )

**Comment by fyq00** [comment]
Thanks!
The bug is fixed!
