### ISSUE TITLE
SET CONFIG_ACL_GPU=y; build error

### ISSUE THREAD

**Issue by wmorders** [OAID/Tengine#23]
L../build
../build/libtengine.so: undefined reference to `TEngine::RegisterConv2dOpencl()'
collect2: error: ld returned 1 exit status
Makefile:69: recipe for target '/home/firefly/Desktop/workspace/tengine/build/tools/bin/test_accuracy' failed
make[1]: *** [/home/firefly/Desktop/workspace/tengine/build/tools/bin/test_accuracy] Error 1
make[1]: Leaving directory '/home/firefly/Desktop/workspace/tengine/tools'
Makefile:134: recipe for target 'tools' failed

**Comment by cyberfire** [comment]
@wmorders 

Maybe you can try "make" again, or simply remove the build/ directory and rebuild everything from scratch.

Thanks,

Haitao

**Comment by wmorders** [comment]
hi Haitao 
I try  "make" again ，The buid error is still 
I build it after remove the build/ directory ，The buid error is still 

But i build the project without CONFIG_ACL_GPU=y successfully; and then Open the configuration and remove `rm -r build/driver` and then rebuild; there is no error, Is it my compiler environment?  how i can do for one time?

THS

**Comment by cyberfire** [comment]
@wmorders 

I guess if you follow the steps in https://github.com/OAID/Tengine/blob/master/doc/acl_driver.md, there should be no issue.

Thanks,

Haitao
