### ISSUE TITLE
run bench_sqz in EAIDK610 failed

### ISSUE THREAD

**Issue by BUG1989** [OAID/Tengine#230]
We build the latest master version in the EAIDK610，all the compile is success，but running the bench_sqz is failed.

![image](https://user-images.githubusercontent.com/13964381/77388951-9a6fde00-6dcc-11ea-8db1-6fdebe969f1d.png)

**Comment by RudyFoo** [comment]
however ,Cross-compile on x86 platforms ，and run bench_sqz on EAIDK610 is ok.

**Comment by BUG1989** [comment]
QQ群里，有人报同样的错误……这个问题需要解决。

**Comment by BUG1989** [comment]
Please using the command below.
`cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm64.native.gcc.toolchain.cmake ..`
