### ISSUE TITLE
Tengine only using 50% cpu

### ISSUE THREAD

**Issue by eeyzl5** [OAID/Tengine#236]
I am running optimized MSSD caffe model on ARM cpu using Tengine framework, and it perfectly gives excellent performance. 

But one thing I have noticed is that my Tengine program is not utilizing 100% cpu at runtime, it actually only using 50% instead. 

I have tried both RK3399 and Jetson Nano and it gives the same result. I can confirm that the lighter the model I used the lower resource the cpu utilized. 

So I am wondering is there possible to use 100% cpu for a further performance gain, even if using a light model? Thanks very much!

**Comment by liqi-c** [comment]
You can use env TENGINE_CPU_LIST to assign which CPU to inference .  maybe One CPU looks better . 
configure like this : export TENGINE_CPU_LIST=0
