### ISSUE TITLE
Compile completed in AIO RK-3399 C(AI), can't run the classification demo

### ISSUE THREAD

**Issue by LinkMple** [OAID/Tengine#246]
no matter compiled with aarch64-linux-gnu.toolchain.cmake or arm64.native.gcc.toolchain.cmake,  the classification binary file still can't be executed.

mypath/Tengine/install/examples/ .classifacation -m xxx -i xxxx

![image](https://user-images.githubusercontent.com/53520951/78140911-50869800-745d-11ea-9df1-db623bbe469f.png)

I have compiled the  Tengine source code in x86 linux and succeed in runing /install/examples  classification demo, but why does this not work in my Firefly RK3399?  ε=(´ο｀*)))唉

**Comment by liqi-c** [comment]
I'm sorry for hear that . 
Maybe you need compile tengine in Firefly again .  or you can compile in x86 by configure use aarch64-linux-gnu.toolchain.cmake .

**Comment by LinkMple** [comment]
It seems to be worked after reboot  my RK3399.   The inference time in Mobilenet_v2 is average 80ms on 227*227 image, which faster than the same classification demo in x86-linux-cpu_only(i7 6700) platform.

Thanks for your suggestion. However the reason why the binary file can'nt run last time would not be discoverd. Maybe reboot and try again, for rookies, ACTUALLY solves almost problems.   /[Face with Tears of Joy]

**Comment by liqi-c** [comment]
You can reappear the problem, and then find out the reason 
check the header information of the file through readelf -h or nm command  , and compare the differences .

**Comment by WangFengtu1996** [comment]
@LinkMple  Hi, 
which version of Ubuntu are you using in the rk3399.
