### ISSUE TITLE
failed compilation with protobuf version=3.0.2

### ISSUE THREAD

**Issue by peyer** [OAID/Tengine#26]
@HEGALLIS , Recently, I compiled prototuf(version =3.0.2) with arm64_v8a and 64 bit target successfully, However, when I added local parameter PROTOBUF_DIR to android_build_armv8.sh and compiled Tengine,  it shown that no match info .
Could you tell me  the required version of protobuf needed by Tengine?

**Comment by cyberfire** [comment]
@peyer 

The pre-built probobuf library is 3.0.0.  Please make sure the protoc in your host machine(x86) is the same as the cross-build probobuf.

Thanks,

Haitao
