### ISSUE TITLE
How to use tmfile for YOLOV3 inference

### ISSUE THREAD

**Issue by guoqiang0148666** [OAID/Tengine#281]
Thanks for you excellent works

l use tegine v1.12.0 and build yolov2 on ubuntu x86_64 platform.

l find the yolov2 support yolov2 caffe format model to infer and your model zone provides yolov3 model in darknet format and tengine format (.tmfile).

So, l have a question is that how to use these yolov3 model, is these some tutorial? 

Any sugesstion will be welcomed, Thanks.

**Comment by maxritter** [comment]
Would be great to have a simple example for yolo object detection :) 
Model conversion already worked
