### ISSUE TITLE
Wiki issue

### ISSUE THREAD

**Issue by tkircher** [OAID/Tengine#286]
In the directions for compilation, instructions for both x86 and arm are titled 'Compile Tengine on Linux x86'

**Comment by pierricklee** [comment]
Hi Thomas,

Do you mean this part? 

> 4. Cross-compile Arm32 / 64 Android version on x86 (Ubuntu)

This is the insturction of `How to complie an Arm-based Andriod version Tengine based on a x86 Ubuntu machine`.

**Comment by tkircher** [comment]
Sorry if I wasn't precise enough. I just took a screenshot to explain what I mean.
![tengine_x86](https://user-images.githubusercontent.com/19326823/81132649-a7b7d680-8efb-11ea-88e4-f24d4e7d4ff1.png)

**Comment by pierricklee** [comment]
Already fixed.

Thank you Thomas!
