### ISSUE TITLE
segfault in test_reduction

### ISSUE THREAD

**Issue by tkircher** [OAID/Tengine#287]
In test_reduction.cpp:

int main(int argc, char* argv[])
{
    init_tengine();

    graph_t graph = create_graph(nullptr, "tengine", model_name.c_str());
    set_graph_layout(graph, TENGINE_LAYOUT_NHWC);
    if(graph == nullptr)
    {
        std::cout << "Create graph0 failed\n";
        return 1;
    }

There is no check to make sure graph isn't null, in the case of the model file not being present, which makes set_graph_layout() fail.

**Comment by pierricklee** [comment]
Thank you Thomas !

This is a valuable suggestion. Also, please feel free to submit PRs if you find anything wrong.
