### ISSUE TITLE
Is there a plan to support android build?

### ISSUE THREAD

**Issue by pedant** [OAID/Tengine#3]
Current version only support build on arm platform， don't support cross-compile arm package on x86 pc platform， Is there a plan to support android build or iOS?

**Comment by cyberfire** [comment]
@pedant 
We do have a plan to create Android build, which is probably released in Q1. 
As for iOS, it is still under discussion.

Thanks,

Haitao

**Comment by pedant** [comment]
waiting for that,  thanks a lot!

**Comment by Ood-Tsen** [comment]
Is there any plan to porting it on freeRTOS ?

**Comment by cyberfire** [comment]
@Ood-Tsen 

Currently, we do not have such plan yet.

Thanks,

Haitao

**Comment by zhangliming0113** [comment]
> it is still under discussion.

is there plan to support iOS build?
