### ISSUE TITLE
海思hi3556av100编译出错

### ISSUE THREAD

**Issue by qq297110281** [OAID/Tengine#314]
很好的项目，最近在尝试移植到hi3556av100 这个平台上是编译一直报：
/opt/hisi-linux/x86-arm/arm-himix200-linux/lib/gcc/arm-linux-gnueabi/6.3.0/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI. Please use -mfloat-abi=softp or -mfloat-abi=hard"
#error "NEON intrinsics not available with the soft-float ABI. Please use -mfloat-abi=softp or -mfloat-abi=hard"

尝试按照提示修改mfloat-abi=softp or -mfloat-abi=hard 都不行。请问有什么建议么？

**Comment by qq297110281** [comment]
解决了，项目CMakeList.txt中对于arm32的编译选项并不能直接应用在hi3556av100上，应该改成：add_definitions(-mcpu=cortex-a53 -mfloat-abi=softfp -mfpu=neon-vfpv4 -mfp16-format=ieee)
即：
![image](https://user-images.githubusercontent.com/8348315/84358234-6f41a180-abf9-11ea-9853-24ff4ad2c3ce.png)

**Comment by northeastsquare** [comment]
请问在海思平台跑起后，可以使用海思平台NNIE加速吗
