### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by enjustli** [OAID/Tengine#327]
https://github.com/OAID/Tengine/blob/v1.12.0/executor/operator/ref/ref_transpose.cpp#L91

长时间运行后，这个队列会不会非常大？

**Comment by enjustli** [comment]
就是一个程序，不停的输入图片进行神经网络推理。连续跑几天几周这种

**Comment by liqi-c** [comment]
op_param.permute.clear();
    for(int i = 0; i < tr_size; i++){
        op_param.permute.push_back(param_->tr_shape[i]);
    }
..........
    op_param.in_dims.clear();
    for(int i = 0; i < (int)in_dims.size(); i++){
        op_param.in_dims.push_back(in_dims[i]);
    }

麻烦加上如上的代码，然后测试看看，谢谢 ~  
如何可以，欢迎pr到我们master

**Comment by skxie** [comment]
>     op_param.permute.clear();
>     for(int i = 0; i < tr_size; i++){
>         op_param.permute.push_back(param_->tr_shape[i]);
>     }
> ..........
>     op_param.in_dims.clear();
>     for(int i = 0; i < (int)in_dims.size(); i++){
>         op_param.in_dims.push_back(in_dims[i]);
>     }
> 
> 麻烦加上如上的代码，然后测试看看，谢谢 ~
> 如何可以，欢迎pr到我们master

这个`clear()`是不是最好加在`Postrun()`里面？

**Comment by liqi-c** [comment]
> > op_param.permute.clear();
> >     for(int i = 0; i < tr_size; i++){
> >         op_param.permute.push_back(param_->tr_shape[i]);
> >     }
> > ..........
> >     op_param.in_dims.clear();
> >     for(int i = 0; i < (int)in_dims.size(); i++){
> >         op_param.in_dims.push_back(in_dims[i]);
> >     }
> > 麻烦加上如上的代码，然后测试看看，谢谢 ~
> > 如何可以，欢迎pr到我们master
> 
> 这个`clear()`是不是最好加在`Postrun()`里面？

不用，在run的时候会多次调用，此时需要clear

**Comment by enjustli** [comment]
添加这个后，已经没有泄露了

**Comment by enjustli** [comment]
这样修改后，会对推理结果有影响么

**Comment by liqi-c** [comment]
> 这样修改后，会对推理结果有影响么

不会的
