### ISSUE TITLE
ERROR: cannot find load function for operator: Sigmoid

### ISSUE THREAD

**Issue by ghimiredhikura** [OAID/Tengine#34]
Hello,

I was testing some version of MobileNetV2 in tengine and got error as in title. looks like there is no function for operator Sigmoid. Any solution?

**Comment by lyuchuny3** [comment]
I'd like to know your mobilenetv2 is caffemodel/tensorflow/mxnet, any link for your deploy model?

**Comment by ghimiredhikura** [comment]
its caffemodel. here is .caffemodel and .prototxt
https://drive.google.com/drive/folders/1mbs_u8to4bPycUk2coUiXuXb-IduT5EW

**Comment by lyuchuny3** [comment]
You can implemenet this layer yourself, ref: https://github.com/OAID/Tengine/blob/master/doc/operator_dev.md . This doc shows you how to implement a new layer step-by-steps.

And we will take this model into consideration for our `to_support_models`. Thanks.

**Comment by ghimiredhikura** [comment]
Thanks.
