### ISSUE TITLE
failed to execute "init_allocator_registry" when load dynamic library.

### ISSUE THREAD

**Issue by atranitell** [OAID/Tengine#367]
Hi,

I had ever used dlopen to call the tengine-lite.so.
However,

```c++
REGISTER_DEV_ALLOCATOR(register_cpu_allocator);
```

It seems to failed to initalize the allocator by such usage;

I try to use below method to calling and go well.
```c++
static void __attribute__((constructor)) register_cpu_allocator_library_init() {
    register_cpu_allocator();   
}

// REGISTER_DEV_ALLOCATOR(register_cpu_allocator);
````

----

Another issue is:

if would the fashion by using dlopen/dlclose break the memory allocating of tengine-lite?

When I test the graph "AlexNet/Inception-V1/Inception-V2/..." sequentially, the program encounters the segmentation error for memory allocator issue.

Best,
KJ

**Comment by kalcohol** [comment]
Hi atranitell, 
    this issue was fixed after https://github.com/OAID/Tengine/pull/373.
    pls checkout master and verify.

many thanks.
