### ISSUE TITLE
cannot find x86.gcc.toolchain.cmake

### ISSUE THREAD

**Issue by zjd1988** [OAID/Tengine#374]
按照https://github.com/OAID/Tengine/wiki 中步骤
在x86 linux编译tengine时，发现找不到x86.gcc.toolchain.cmake 文件
erro log
xj-zjd@ubuntu1604:~/work_space/self_work/tengine/build$ cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/x86.gcc.toolchain.cmake ..
-- CMAKE_INSTALL_PREFIX = /home/xj-zjd/work_space/self_work/tengine/build/install
CMake Error at /usr/local/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file: ../toolchains/x86.gcc.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:41 (ENABLE_LANGUAGE)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

查看了下toolchain目录发现，确实找不到对应文件，在整个repo也没有找到此文件

**Comment by zjd1988** [comment]
此外，我在aarch64板子编译代码也未出现convert_model_to_tm可执行程序
还有一个小瑕疵，https://github.com/OAID/Tengine/wiki 网页中
make –j4 中j应该字符使用的编码方式有问题，直接拷贝到本地命令行，执行会报错
make: *** No rule to make target '–j4'.  Stop.

**Comment by zchrissirhcz** [comment]
wiki对应的是master分支。x86.gcc.toolchain.cmake在这里https://github.com/OAID/Tengine/blob/master/toolchains/x86.gcc.toolchain.cmake 

目前默认的分支是tengine-lite，不用指定x86 toolchian即可编译。

**Comment by BUG1989** [comment]
> wiki对应的是master分支。x86.gcc.toolchain.cmake在这里https://github.com/OAID/Tengine/blob/master/toolchains/x86.gcc.toolchain.cmake
> 
> 目前默认的分支是tengine-lite，不用指定x86 toolchian即可编译。

是的，Tengine Lite 现在直接 cmake 编译即可

**Comment by zjd1988** [comment]
@zchrissirhcz  @BUG1989  谢谢二位，今天试试。
