### ISSUE TITLE
tm2_serializer.c 代码疑问

### ISSUE THREAD

**Issue by zjd1988** [OAID/Tengine#402]
看unload_graph函数实现中有调用munmap函数，但是搜了下整个代码并没有调用mmmap地方，有一处也被注释了，是不是忘记注释掉mumap呢？

还有就是load_model函数中读文件改成fopen接口，是不是比较好做windows的移植呢？

**Comment by zjd1988** [comment]
windows下需要包含io.h ,就能调用read open等函数，加宏控制即可

**Comment by kalcohol** [comment]
it's been fixed in https://github.com/OAID/Tengine/pull/405 by yourself. many thanks.
