### ISSUE TITLE
关于dtype推导的处理

### ISSUE THREAD

**Issue by feiyuvl** [OAID/Tengine#403]
hi，tengine里怎么处理每个op中tensor的dtype（float/fp16/int8），在nnvm里有infer_type函数，根据输入dtype推导输出dtype，tengine里只看到infer_shape函数

**Comment by BUG1989** [comment]
在转换模型生成 tmfile 的时候已经制定好了

**Comment by feiyuvl** [comment]
现在模型转化（图优化）和运行是分离的，后面是否有计划做在线图优化和执行的计划？

**Comment by kalcohol** [comment]
> 现在模型转化（图优化）和运行是分离的，后面是否有计划做在线图优化和执行的计划？

有的，不过目前优先级比较低……
