### ISSUE TITLE
DTENGINE_DEBUG_TIME=ON not works

### ISSUE THREAD

**Issue by destinyzs** [OAID/Tengine#406]
[here](https://github.com/OAID/Tengine/blob/tengine-lite/doc/faq.md#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E6%A8%A1%E5%9E%8B%E5%90%84%E4%B8%AAlayer%E8%80%97%E6%97%B6) say this flag can display the time consumption of each layer.

However, i tried both based on cpu and opencl, no one works.

**Comment by BUG1989** [comment]
@destinyzs Please add this line `set_log_level(LOG_INFO);` after `init_tengine()`

```
    /* inital tengine */
    if (init_tengine() != 0)
    {
        fprintf(stderr, "Initial tengine failed.\n");
        return -1;
    }
    fprintf(stderr, "tengine-lite library version: %s\n", get_tengine_version());

    set_log_level(LOG_INFO);
```
