### ISSUE TITLE
 Tengine Lite架构设计理念

### ISSUE THREAD

**Issue by yyqgood** [OAID/Tengine#410]
你好, Tengine Lite有架构设计理念的Paper吗?

**Comment by un-knight** [comment]
我也在找，不过貌似官方应该是没有的。

**Comment by QingChuanWS** [comment]
Tengine的编码风格还是很nice的, 可以读一下源码, 学习一下

**Comment by yyqgood** [comment]
@QingChuanWS 我想快速的获取; 也谢谢你的提议!

**Comment by TheWangYang** [comment]
请问关于Tengine这个框架的相关论文有哪些？找了很久一直找不到
