### ISSUE TITLE
failed to set node ops for node: 413 op: Interp

### ISSUE THREAD

**Issue by azuredsky** [OAID/Tengine#456]
tengine 1.12  linux x86 
use models：
[faceDetector_sim.zip](https://github.com/OAID/Tengine/files/5442670/faceDetector_sim.zip)

failed to set node ops for node: 413 op: Interp
/work/Tengine_build/1.12/Tengine_x86_linux/executor/lib/graph_task.cpp:234 failed to Prerun task on  dev executor: x86.probed

**Comment by BUG1989** [comment]
Please try tengine lite version, thanks.
