### ISSUE TITLE
Can it be built on devices not having ARM?

### ISSUE THREAD

**Issue by AbyShk95** [OAID/Tengine#46]
Awesome work:)
Can I build Tengine on a PC with AMD64? Or does it work only on ARM architecture?
Thank you:)

**Comment by lyuchuny3** [comment]
Yes, you can build Tengine on  PC with AMD64 by setting `Makefile.config` as:
* close arch64 option: `#CONFIG_ARCH_ARM64=y`
* open blas option: `CONFIG_ARCH_BLAS=y`

Detail installation guild see https://github.com/OAID/Tengine/blob/master/doc/install.md
Thanks

**Comment by AbyShk95** [comment]
Thank you so much :)

**Comment by nopattern** [comment]
I build the Tengine lib successfully . It failed when running ./build/tests/bin/bench_sqz  r1. 
The error info is 'Segmentation Fault(core dumped)'
