### ISSUE TITLE
aarch64-linux 编译出错

### ISSUE THREAD

**Issue by quinnrong94** [OAID/Tengine#484]
tengine-lite分支最新代码编译失败，错误信息:
Tengine/src/dev/cpu/op/conv/cortex_a/conv_kernel_int8_arm.c:268:10: error: incompatible types when assigning to type ‘int32x4_t’ from type ‘float32x4_t’
     out0 = vmulq_n_f32(out0_f, outputscales);

**Comment by shitouren1994** [comment]
收到

**Comment by BUG1989** [comment]
@quinnrong94 已修复，请再试一试 #485
