### ISSUE TITLE
项目自带的所有的例子都可以在 khadas vim3 上面跑通嘛  ？？？

### ISSUE THREAD

**Issue by Jiakui** [OAID/Tengine#495]
项目自带的所有的例子都可以在 khadas vim3 上面跑通嘛  ？？？

**Comment by PureHing** [comment]
@Jiakui  我试了一下，cpu可以

**Comment by Jiakui** [comment]
CPU  好像确实可以。。。。NPU 不行啊 。。。。

**Comment by Jiakui** [comment]
QQ 群里的回复是 ，NPU “正在测试，测完了就发出来了”

**Comment by PureHing** [comment]
展望一下元旦吧

**Comment by BUG1989** [comment]
NPU 版本已经发给 Khadas 了，不清楚他们什么时候 Release 出来呀

**Comment by BUG1989** [comment]
#546
