### ISSUE TITLE
about branching network(MTCNN) 

### ISSUE THREAD

**Issue by bjthemost** [OAID/Tengine#50]
hi:
  i'm running a network, like this 

     input
           |
     |               |
conv1            |
relu1             |
     |               |
pool1         conv1-2
    \             relu1_2  
     \                 /
      \              /
         concat1
               |
          conv2
          relu2
              .
              .
              .
              .

with tengine/build/examples/mtcnn/MTCNN ....
she is saying:
/sfbak/tengine/examples/build/mtcnn/MTCNN
ACL Driver Initialized
ACL Graph Initialized
Driver: ACLGraph probed 1 devices
Driver: ACLDriver probed 1 devices
tensor: prob1 created by node: prob1 is not consumed
add the node: prob1 into output list
tensor: conv4-2 created by node: conv4-2 is not consumed
add the node: conv4-2 into output list
load PNet model done!
tensor: prob1 created by node: prob1 is not consumed
add the node: prob1 into output list
tensor: fc5-2 created by node: fc5-2 is not consumed
add the node: fc5-2 into output list
load RNet model done!
tensor: prob1 created by node: prob1 is not consumed
add the node: prob1 into output list
tensor: fc6-2 created by node: fc6-2 is not consumed
add the node: fc6-2 into output list
tensor: fc6-3 created by node: fc6-3 is not consumed
add the node: fc6-3 into output list
load ONet model done!

### Segmentation fault (core dumped)
:(

**Comment by hey-yahei** [comment]
Can you run the same model on cpu successfully?

**Comment by bjthemost** [comment]
yes, i can.
