### ISSUE TITLE
Run time out of 7200

### ISSUE THREAD

**Issue by goe789** [OAID/Tengine#511]
加载模型后 发现超过两个小时就报错
Run time out of 7200
Run graph failed
请问这怎么解决

**Comment by BUG1989** [comment]
@goe789 请问是什么时候的版本？

**Comment by goe789** [comment]
tengine-nnie Tengine1.7版本

**Comment by BUG1989** [comment]
试用版本吗？

**Comment by goe789** [comment]
http://www.tengine.org.cn/info.php?class_id=105105
从这个地址下载的 基于海思3516CV500硬件平台的Linux开发者版本

**Comment by BUG1989** [comment]
开发者版本是试用版本，的确有2小时限时的限制

**Comment by goe789** [comment]
请问该用甚么版本，是付费的吗

**Comment by BUG1989** [comment]
是的，现在还有用 NNIE 的需求吗？不是已经停产了吗？

**Comment by goe789** [comment]
还有一些货，有需求的，请问怎么付费，how much

**Comment by BUG1989** [comment]
@goe789 请问您现在还有需求吗？部署的是什么模型呢
