### ISSUE TITLE
crtdefs.h: No such file or directory

### ISSUE THREAD

**Issue by kjcx100** [OAID/Tengine#513]
我按照compile.md编译：
cd Tengine-Lite
mkdir build 
cd build
cmake ..
make
make install
以及编译aarch64
cd Tengine-Lite
mkdir build 
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-linux-gnu.toolchain.cmake ..
make
make install

都出现找不到crtdefs.h文件，我看这是在getopt.h里面包含的，我还发现里面包含windows.h文件，这不是VC目录下的头文件吗，我编译Linux版本咋会包含这些呢？

**Comment by BUG1989** [comment]
@kjcx100 最新版本应该修复了，请再试试？谢谢。

**Comment by kjcx100** [comment]
修复了
