### ISSUE TITLE
Windows平台运行示例程序出现”Tengine: No available device.“错误

### ISSUE THREAD

**Issue by Charyun** [OAID/Tengine#517]
在Windows平台运行Tengine-lite的示例程序 tm_yolact.cpp，出现`”Tengine: No available device.“`的错误，请问如何解决？

**Comment by BUG1989** [comment]
release模式还是debug模式呢

**Comment by Charyun** [comment]
> release模式还是debug模式呢

release模式

**Comment by BUG1989** [comment]
@CharyPro 

Please try the latest version. We already support it.

And if that doesn't work, please reopen it.
