### ISSUE TITLE
tengine 现在支持哪些 NPU ？？？

### ISSUE THREAD

**Issue by Jiakui** [OAID/Tengine#528]
好像  VIM3 上面的 NPU 还不支持。。。哪些 NPU 现在是 tengine 可以直接支持的 ？？？ 求推荐。。。

**Comment by Pony23333** [comment]
同问，QQ群资料里面有个VIM3的包，但是没有说明文档，不知道怎么用，也不知道NPU上运行效果怎么样

**Comment by Pony23333** [comment]
另外跟瑞芯微合作的两款芯片也有新闻，但是估计没有开源https://zhidx.com/p/238028.html

**Comment by BUG1989** [comment]
Khadas VIM3 NPU 的支持已经开源，请尝试 #546
