### ISSUE TITLE
请问现在支持amlogic a311d芯片吗

### ISSUE THREAD

**Issue by aqzwss** [OAID/Tengine#557]

**Comment by BUG1989** [comment]
@aqzwss A311D 的 CPU、GPU、NPU 目前均已支持
CPU：默认 armv8.1 CPU 性能算子
GPU：https://github.com/OAID/Tengine/blob/tengine-lite/doc/gpu_acl_user_manual.md
NPU：https://github.com/OAID/Tengine/blob/tengine-lite/doc/npu_tim-vx_user_manual.md
