### ISSUE TITLE
android gpu support

### ISSUE THREAD

**Issue by gunjupark** [OAID/Tengine#56]
I want to run yolov2-tiny in android (galaxy s9) with ACL ,Mali-gpu G72

but in CMakeList, there is no option for build Tengine with ACL.

Do you have any plan or support for android GPU acceleration with ACL??

**Comment by cyberfire** [comment]
@gunjupark 

Yes. We are working on it and hope it will be released soon.

Thanks,

haitao

**Comment by gunjupark** [comment]
Thanks
