### ISSUE TITLE
Tengine and TIM-VX utilitze only NPU?

### ISSUE THREAD

**Issue by janoslim** [OAID/Tengine#569]
Hello,
I am using Tengine with TIM-VX on vim3 A311d,
and I test vgg19 quantized model and its latency is 36ms which is quite fast.
And I wonder Tengine use only NPU running model or utilizing cpu gpu npu or cpu npu both on inference time using scheduling or sth.
Thank you!

**Comment by kalcohol** [comment]
Tengine has finished some additional work, so a model could use npu and cpu both.
if model not fully supported by npu, Tengine will split it to several parts, some parts will be running on npu, the other will be running on cpu.
Tengine also support gpu, see [ACL backend](https://github.com/OAID/Tengine/blob/tengine-lite/doc/gpu_acl_user_manual.md) for more detials.
