### ISSUE TITLE
how to install google-glog on RK3399 platform

### ISSUE THREAD

**Issue by jackhouchina** [OAID/Tengine#57]
hi, i want to install Tengine on RK3399 platform according [document](https://github.com/OAID/Tengine/blob/master/doc/install.md) , but always failure at install libgoogle-glog-dev package ,would you help me to slove it, thanks very much!

**Comment by cyberfire** [comment]
@jackhouchina 
Maybe you can update your repo first by
sudo apt update

and then have a try.

Thanks,
Haitao
