### ISSUE TITLE
tim-vx libOpenVX.so issue

### ISSUE THREAD

**Issue by stevenwudi** [OAID/Tengine#575]
When I make -j4 using tim-vx, I have encounter the following issue

`
Tengine/3rdparty/tim-vx/lib/x86_64/libOpenVX.so: file format not recognized; treating as linker script
`

Any idea how to solve it? Many thanks in advance for your answer.

**Comment by kalcohol** [comment]
please join our QQ group(829565581) add share more info for help, this offen happend when someone cross-compile Tengine for a pecial device.

**Comment by stevenwudi** [comment]
I have added the QQ group and answer CNN, hope 圈圈虫 will verify soon. Thanks

**Comment by kalcohol** [comment]
solved in group.
