### ISSUE TITLE
Tengine_models

### ISSUE THREAD

**Issue by h3retek** [OAID/Tengine#577]
Hi,

I cannot download the [Tengine_models](https://pan.baidu.com/s/1Ar9334MPeIV1eq4pM1eI-Q#list/path=%2F) from Baidu. Is there another mirror available somewhere?

**Comment by Adhithya-tech** [comment]
Nope

**Comment by Adhithya-tech** [comment]
You can try the benchmark models provided

**Comment by h3retek** [comment]
Thanks
