### ISSUE TITLE
vim3的npu不支持PreLU算子的问题

### ISSUE THREAD

**Issue by wuqiangch** [OAID/Tengine#579]
我的模型里面prelu算法，量化为uint8，在vim3的npu上面运行出现以上问题。但是我又把prelu替换为relu，又出现其他错误：
kernel_selector:906]Not found kernel "add"
E [compute_node:354]Create node[6] ADD fail
有遇到过这样子的问题吗？

**Comment by wuqiangch** [comment]
代码更新解决了Add的问题，但是prelu仍然不支持。带有prelu的算子提示一下错误：  
ERROR: Failed to compile vx shader. (error: FFFFFFFF)
E [_gpu_register:476]Build program fail.
E [vsi_nn_kernel_create_node:631]Register client kernel com.vivantecorp.extension.evis.prelu_U8F16toU8_2D fail with -1.

(10:0) : error : Error(0,10) : Cannot find the header file cl_viv_vx_ext.h.
(200:0) : error : Error(0,200) : Cannot find the header file cl_viv_vx_ext.h.
(203:0) : error : syntax error at 'VXC_512Bits'

**Comment by BUG1989** [comment]
需要将 cl_viv_vx_ext.h 拷贝到执行文件的路径下，为什么呢？prelu 的算子是在线编译生成的.......
