### ISSUE TITLE
CONFIG_OPT_CFLAGS is not appended to CMAKE_C_FLAGS

### ISSUE THREAD

**Issue by ml-inory** [OAID/Tengine#588]
Branch: [master](https://github.com/OAID/Tengine/tree/master)
Compiler: arm-himix200-linux-gcc
Platform: Ubuntu 18.04

compile instruction:
```
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/himix200.toolchain.cmake
make -j4
```

Got error:
```
/opt/hisi-linux/x86-arm/arm-himix200-linux/lib/gcc/arm-linux-gnueabi/6.3.0/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softp or -mfloat-abi=hard"
```

Check toolchains/himix200.toolchain.cmake:
Line 14:
```
SET (CONFIG_OPT_CFLAGS "-mfloat-abi=softfp")
```

But ```CONFIG_OPT_CFLAGS``` is NOT found in top level CMakeLists.txt, which makes float-abi not set.

I currently solved it by adding add_definitions(${CONFIG_OPT_CFLAGS}) in CMakeLists.txt.

**Comment by BUG1989** [comment]
@ml-inory 

Please try the latest version.
