### ISSUE TITLE
lstm支持情况

### ISSUE THREAD

**Issue by YoohJH** [OAID/Tengine#592]
请教几个问题：
1.Tengine对lstm的支持情况如何
2. 有没有对各个模块详细的文档
3. 直接加载caffe模型，涉及的是serializer模块还是tengine-module
4. libcaffe-serializer.so库如何编译，用来做什么，现在的文档都没有提到

感谢！

**Comment by BUG1989** [comment]
@leejoin 

1. 目前 Tengine 对 LSTM 对齐的是 ONNX 实现
2. [在线文档](https://tengine-docs.readthedocs.io/zh_CN/latest/)
3. 需要通过 convert_tool 将 caffe 模型转换为 Tengine 的模型格式 tmfile
4. libcaffe-serializer.so 不再使用
