### ISSUE TITLE
Different class color based detection.

### ISSUE THREAD

**Issue by rahulsharma11** [OAID/Tengine#60]
Hi, i am using ssd model for object detection. All detected objects are placed inside green color boundry.
Any help to make it different box for different objects?
Thanks.

**Comment by lyuchuny3** [comment]
Hi, you can change the color here https://github.com/OAID/Tengine/blob/master/examples/mobilenet_ssd/mssd.cpp#L114

`cv::rectangle(img, cv::Rect(box.x0, box.y0,(box.x1-box.x0),(box.y1-box.y0)),cv::Scalar(255, 255, 0),line_width);`

you can set other color `cv::Scalar(255, 255, 0)` according to `box.class_idx` by yourself.

**Comment by rahulsharma11** [comment]
Thanks.
