### ISSUE TITLE
[Typo] in IOU in tm_retinaface.cpp

### ISSUE THREAD

**Issue by qinhj** [OAID/Tengine#623]
https://github.com/OAID/Tengine/blob/bdcf5c9d850d4199109787bdb35cd848fce813e2/examples/tm_retinaface.cpp#L141

which should be:
    float yy2 = std::min(a.rect.y + a.rect.h, b.rect.y + b.rect.h);

**Comment by qinhj** [comment]
https://github.com/OAID/Tengine/blob/8f25ee3541f182832a46df21e4ccea9df8f2827d/examples/tm_retinaface.cpp#L141

**Comment by BUG1989** [comment]
Merged #629
