### ISSUE TITLE
onnx 模型转换成功但是推理core dump，这种问题怎么排查

### ISSUE THREAD

**Issue by fwz-fpga** [OAID/Tengine#635]
一层一层查？有没有高效方法

**Comment by BUG1989** [comment]
@fwz-fpga 

编译时，` cmake -DTENGINE_DEBUG_TIME=ON ..`  可使能单层运行时耗时统计，能变相找出跑到哪一层挂掉了。

**Comment by zylo117** [comment]
It failed to build with -DTENGINE_DEBUG_TIME=ON, "Tengine/source/device/cpu/cpu_device.c:143:80: error: struct op has no member named op_type; did you mean type"
