### ISSUE TITLE
quant_tool bug?

### ISSUE THREAD

**Issue by zylo117** [OAID/Tengine#659]
1. some resolution is not supported?
I tried to convert my models to quantized tmfile. When using quant_tool_int8, the models can convert successfully with resolution smaller than 512x512, like 384x384, 256x256, 480x480, 512x128, but not 512x512.
`Segmentation fault`

2. quant_tool_uint8 crashed but quant_tool_int8 doesn't
when converting models to uint8, the program crashed.
```
malloc(): memory corruption
Aborted
```

**Comment by BUG1989** [comment]
Don't worry, both tools are set to open source this month.

**Comment by BUG1989** [comment]
已开源。
