### ISSUE TITLE
Model Zoo download from overseas

### ISSUE THREAD

**Issue by mtx512** [OAID/Tengine#676]
Hi,

Without a baidu account the model zoo can't be downloaded from overseas is it possible to upload to google cloud or another provider?

**Comment by BUG1989** [comment]
@mtx512  Does this work? https://drive.google.com/drive/folders/1hunePCa0x_R-Txv7kWqgx02uTCH3QWdS?usp=sharing

**Comment by mtx512** [comment]
Great that works!
