### ISSUE TITLE
tengine yolov5s onnx 优化更新

### ISSUE THREAD

**Issue by standy-zz** [OAID/Tengine#726]
@BUG1989 你好。文章【Tengine 支持 NPU 模型部署-YOLOv5s（https://zhuanlan.zhihu.com/p/360138163?utm_medium=social&utm_oi=815507548294770688）】      里提到的onnx模型官方回复已不再支持，从原始pt转化为onnx，或者基于自定义数据训练后得到的pt文件转onnx后，模型结构和之前不一样，麻烦更新下脚本文件，不胜感谢。

**Comment by qinhj** [comment]
@standy-zz @BUG1989
$ wget https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt -O yolov5s.v5.pt # [yolov5](https://github.com/ultralytics/yolov5)
$ python3 [models/export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py) --weights yolov5s.v5.pt --simplify
$ python3 [yolov5s-opt.py](https://github.com/OAID/Tengine/tree/tengine-lite/tools/optimize/yolov5s-opt.py) --input yolov5s.v5.onnx --output yolov5s.v5.opt.onnx --in_cut_name 167 --out_cut_names 397,458,519

**Comment by qinhj** [comment]
Hi~ @BUG1989 I've updated the yolov5s-opt.py and add some scripts for yolov3 [here](https://github.com/qinhj/Tengine/tree/qinhj/tools/optimize). If you want, I can create a pr.

**Comment by BUG1989** [comment]
@qinhj Thanks for your contribution!

**Comment by standy-zz** [comment]
@qinhj @BUG1989 感谢感谢！！！

现在转换量化过程正常了，详细过程如下：
1、wget https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt -O yolov5s.v5.pt # yolov5
2、python3 models/export.py --weights yolov5s.v5.pt --simplify
3、python3 yolov5s-opt.py --input yolov5s.v5.onnx --output yolov5s.v5.opt.onnx --in_cut_name 167 --out_cut_names 397,458,519
4、convert_tool -f onnx -m yolov5s.v5.opt.onnx -o yolov5s.v5.opt.tmfile
5、./quant_tool_uint8 -m yolov5s.v5.opt.tmfile -i verify-phone -o yolov5s_v5_320_opt_uint8.tmfile -g 12,160,160 -w 0,0,0 -s 0.003921,0.003921,0.003921 -c 0 -k 1 -t 6 -y 320

官方训练好的模型耗时如下：
...
tensor name 439
tensor name 456
 vx_shape 5 85 0 0
tensor name 378
tensor name 395
 vx_shape 5 85 0 0
tensor name 518
tensor name 457
tensor name 396
Repeat 1 times, thread 1, avg time 1060.21 ms, max_time 1060.21 ms, min_time 1060.21 ms
--------------------------------------
detection num: 4
16:  78%, [ 132,  220,  309,  544], dog
 2:  66%, [ 469,   76,  686,  167], car
 1:  50%, [ 131,  129,  579,  428], bicycle
58:  39%, [  57,   84,  110,  133], potted plant

识别结果如下
![yolov5_timvx_letterbox_out_new_org](https://user-images.githubusercontent.com/192710/121480905-2d129200-c9fe-11eb-9ad4-c2c20be1ddf1.jpg)



还有几个疑问：
1、怎么关掉输出信息，源码在timvx_executor.cc？
2、耗时和之前发布的差异有点大，这是因为输出日志导致的吗？
3、从图片效果看，精度下降有点多呢？

烦请大神帮忙解答下，谢谢啦。

**Comment by standy-zz** [comment]
把日志屏蔽后，基于自定义数据迭代的模型实测性能如下：

Repeat 100 times, thread 4, avg time 47.27 ms, max_time 53.23 ms, min_time 46.51 ms
--------------------------------------
detection num: 2

收工，感谢大佬 @qinhj @BUG1989
