### ISSUE TITLE
How can I train custom mobilenet ssd model?

### ISSUE THREAD

**Issue by gunjupark** [OAID/Tengine#73]
I want to get custom MobileNetSSD_deploy.caffemodel which can be run on Tengine

So I trained my custom model following this referrence site 
https://github.com/chuanqi305/MobileNet-SSD

But in Tengine's MobileNet prototxt , BatchNorm op doesn't exist.

so could you upload your MobileNet_train.prototxt 

Thank you

**Comment by gunjupark** [comment]
I found no_bn.prototxt 
thankyou

**Comment by lyuchuny3** [comment]
Hi， 
You can run `merge_bn` to merge batchnorm op into conv
```
python merge_bn.py --model example/MobileNetSSD_deploy.prototxt --weights snapshot/mobilenet_iter_xxxxxx.caffemodel
```
Details see https://github.com/chuanqi305/MobileNet-SSD/blob/master/README.md#train-your-own-dataset   step6.

**Comment by gunjupark** [comment]
Thank you

**Comment by KrishnaShalini0518-arch** [comment]
Hi @gunjupark,

Could you share the references you used for training Tengine model?
