### ISSUE TITLE
a311d vim3 系统镜像更新后 运行失败

### ISSUE THREAD

**Issue by standy-zz** [OAID/Tengine#751]
vim3 系统镜像信息如下：
root@Khadas:/data/work/# cat /etc/fenix-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=VIM3
VENDOR=Amlogic
VERSION=1.0.6
ARCH=arm64
INITRD_ARCH=arm64
INSTALL_TYPE=SD-USB
IMAGE_VERSION=V1.0.6-210520
################ GIT VERSION ################
UBOOT_GIT_VERSION=khadas-vims-v1.0.6-release
LINUX_GIT_VERSION=khadas-vims-v1.0.6-release
FENIX_GIT_VERSION=v1.0.6
#############################################

tengine 运行结果如下：

root@Khadas:/data/work# tm_yolov5s_timvx  -m best_v10_320_opt_uint8.tmfile  -i verify/part1_117.jpg 
tengine-lite library version: TE-BU-P3002-Khadas-v1.0-R20201210
not found device add_context_device VSI DEVICE failed.

khadas 官方论坛反馈如下：
https://forum.khadas.com/t/tengine-demo-vim3-210430/12438

还请大佬 @BUG1989  更新适配下，感谢。

**Comment by BUG1989** [comment]
请使用最新 khadas 的版本，最近才更新了
