### ISSUE TITLE
Tengine-Master 分支 Mobilenet_SSD 物体检测无法正常运行

### ISSUE THREAD

**Issue by SwaggyMacro** [OAID/Tengine#763]
### Master分支编译出来的例子 无法正常检测，但是Lite分支编译出来的可以正常检测。
![QQ图片20210624120410](https://user-images.githubusercontent.com/38845682/123200963-5c3bff80-d4e4-11eb-9eda-603bde125520.jpg)
`（Master分支下的Mobilenet_ssd例子）`
![QQ图片20210624120543](https://user-images.githubusercontent.com/38845682/123201041-842b6300-d4e4-11eb-901f-1dffe035177a.jpg)
`（Lite分支下的tm_mobilenet_ssd例子）`

用Python版本写出来的也是有同样的问题
![QQ图片20210624120654](https://user-images.githubusercontent.com/38845682/123201131-ac1ac680-d4e4-11eb-9423-7b8d7ff6a4c3.jpg)
`（左边是Master分支下的Mobilenet_ssd例子，右边是自己用Python写出来的）`

**Master分支下的Mobilenet_ssd例子执行后 似乎把所有的物体都输出出来了，Score甚至577%**
![QQ图片20210624120819](https://user-images.githubusercontent.com/38845682/123201257-dec4bf00-d4e4-11eb-95c2-6b069c7a4dac.png)

是Master分支编译出来的动态库有问题吗？使用libtengine-lite.so就没有问题，模型都是一样的，使用的mobilenet_ssd.tmfile。

**Comment by SwaggyMacro** [comment]
似乎Pytengine并不支持Tengine-Lite，import直接报错了。
![QQ图片20210624121112](https://user-images.githubusercontent.com/38845682/123201443-45e27380-d4e5-11eb-959d-d81492e372d3.jpg)
lib_path是一个空列表[]，如果用libtengine.so的话是会有libtengine.so的路径在lib_path中的 即 lib_path[0]

**Comment by BUG1989** [comment]
请使用 tengine-lite 分支

**Comment by SwaggyMacro** [comment]
> 请使用 tengine-lite 分支

请问tengine-lite有相应的python-api支持吗

**Comment by SwaggyMacro** [comment]
> 请使用 tengine-lite 分支

@BUG1989 请问tengine-lite有相应的python-api支持吗

**Comment by BUG1989** [comment]
已经更新了

**Comment by SwaggyMacro** [comment]
> 已经更新了

@BUG1989 谢谢，测试正常了

**Comment by BUG1989** [comment]
@SwaggyMacro 谢谢反馈结果。

**Comment by SwaggyMacro** [comment]
> @SwaggyMacro 谢谢反馈结果。

@BUG1989 但是每次识别都有一个sofa score有146% 不过坐标在图片外 没有啥影响
![M_AAL~MGI 9X _89BJH2KPP](https://user-images.githubusercontent.com/38845682/123424797-e6bf5480-d5f3-11eb-87c3-ad5d3820636e.png)

**Comment by SwaggyMacro** [comment]
![image](https://user-images.githubusercontent.com/38845682/123424846-f8a0f780-d5f3-11eb-9202-59183eacfd82.png)
