### ISSUE TITLE
Android app run error 

### ISSUE THREAD

**Issue by yanlei08** [OAID/Tengine#77]
Hi,
I build libtengine.so for android arm64 successfully. Then I create a project in Android studio and add libtengine.so into the project. I build the project successfully, but when I run the app in Android Mobile Phone, it crash. If I remove the libtengine.so from  the project. The app become OK.

CMakefile.txt in Android Studio:
add_library(libtengine SHARED IMPORTED )
set_target_properties(libtengine PROPERTIES IMPORTED_LOCATION
                      ${distribution_DIR}/libs/${ANDROID_ABI}/libtengine.so)

Is there anything wrong?
Can you provide a Android App demo?
Thanks very much.

**Comment by hey-yahei** [comment]
Hi, yanlei08
Tengine demo for Android Studio is provided at [Tengine-app](https://github.com/OAID/Tengine-app/tree/master/android/classification) now.
