### ISSUE TITLE
Tengine v0.8.0 with ACL_GPU build

### ISSUE THREAD

**Issue by acdream007** [OAID/Tengine#79]
I used the libarm_compute_core.so and libarm_compute.so in ComputeLibrary/build_64 building libtengine.so success on Android, but when I running, it shows error: 
Could not find library: /opt/Tengine/facerecognition/obj/local/arm64-v8a/libarm_compute_core.so
WARNING: Could not find library: /opt/Tengine/facerecognition/obj/local/arm64-v8a/libarm_compute.so

**Comment by hey-yahei** [comment]
Hi, acdream007
Following [build_android.md](https://github.com/OAID/Tengine/blob/master/doc/build_android.md), have you successfully built Tengine for Android(Step1 - Step5 in the document) and examples([Step6](https://github.com/OAID/Tengine/blob/master/doc/build_android.md#6-build-example)) on Linux, but failed to run examples on Android([Step8.2](https://github.com/OAID/Tengine/blob/master/doc/build_android.md#82-run)) with errors you show in issue?

Thanks

**Comment by acdream007** [comment]
@hey-yahei  
Thanks for your reply.
When I don't link  libarm_compute_core.so and arm64-v8a/libarm_compute.so in the jni library, it can run success.
I encounter another problem, I use mtcnn to detection faces on Snapdragon 835, if I use "set_graph_device(m_recog_graph, "acl_opencl")" on PNet, the process is blocked, How to resolve the problem?
When I use "set_graph_device(m_recog_graph, "acl_opencl")"  only on RNet and ONet , I find it works on cpu not gpu.

**Comment by hey-yahei** [comment]
Hi, acdream007
I'm sorry that ACL has not supported some OPs such as `Permute` in mtcnn yet. What OPs are supported would be found in [wiki - support ops](https://github.com/OAID/Tengine/wiki/%E6%94%AF%E6%8C%81%E7%9A%84OP). However, CPU+GPU is supported now. Maybe you can try to use [Heterogeneous Computing](https://github.com/OAID/Tengine/wiki/GPU-CPU%E5%BC%82%E6%9E%84%E8%B0%83%E5%BA%A6%E8%B7%91MobilenetSSD) to resolve such a problem.
