### ISSUE TITLE
convert yolov5s.onnx 模型失败

### ISSUE THREAD

**Issue by yank666** [OAID/Tengine#807]
转换yolov5s.onnx模型直接失败，segment fault， 是onnx的 slice 不支持吗？

Tengine-Convert-Tools 版本master commit : 51ddcda

yolov5s 模型来源https://github.com/ultralytics/yolov5.git ，采用yolov5s 权重
![image](https://user-images.githubusercontent.com/79586188/124733839-27e62b80-df47-11eb-8c6f-c13fbce25b82.png)

**Comment by qinhj** [comment]
可以参考这里：
https://github.com/OAID/Tengine/tree/tengine-lite/tools/optimize

**Comment by BUG1989** [comment]
@yank666 也可以参考这里：
https://zhuanlan.zhihu.com/p/360138163
里面需要 @qinhj 提及到到 python 工具对 yolov5s.onnx 进行简单的修改，删除 focus 和 后处理（如果有的话）。
