### ISSUE TITLE
build error on RK3399

### ISSUE THREAD

**Issue by polor1010** [OAID/Tengine#84]
I builded on RK3399
the "makfile.config" setting is
ONFIG_ARCH_ARM64=y
CONFIG_OPT_CFLAGS = -O2
#CONFIG_ACL_GPU=y
#CONFIG_ARCH_BLAS=y
...

gcc -v
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10)

error message
/usr/lib/gcc/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) t
  ^
cc1plus: error: unrecognized command line option '-Wno-ignored-attributes' [-Werror]
cc1plus: all warnings being treated as errors
In file included from batch_norm.cpp:34:0:
/usr/lib/gcc/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) t
  ^
cc1plus: error: unrecognized command line option '-Wno-ignored-attributes' [-Werror]
cc1plus: all warnings being treated as errors
In file included from ./include/pooling_kernel.h:27:0,
                 from pooling.cpp:32:
/usr/lib/gcc/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) t
  ^
cc1plus: error: unrecognized command line option '-Wno-ignored-attributes' [-Werror]
cc1plus: all warnings being treated as errors
In file included from batch_norm.cpp:34:0:
/usr/lib/gcc/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) t
  ^
cc1plus: error: unrecognized command line option '-Wno-ignored-attributes' [-Werror]
cc1plus: all warnings being treated as errors
make[4]: Entering directory '/home/pi/tengine/executor/operator/arm64/fc'
g++ -std=c++11   -I./include  -Wno-ignored-attributes -Werror -g -O2 -Wall -g -fPIC  -I/home/pi/tengine/executor/../core/include -I/home/pi/tengine/executor/../include -I/home/pi/tengine/executor/../operator/include  -I/home/pi/tengine/executor/include   -Werror -DCONFIG_ARCH_ARM64=1 -I/home/pi/tengine/executor/operator/include -O3 -funroll-loops  -I../include  -c fully_connected_fast.cpp -o /home/pi/tengine/build/executor/operator/arm64/fc/fully_connected_fast.o
gcc -std=gnu99   -Wno-ignored-attributes -Werror -g -O2 -Wall -g -fPIC  -I/home/pi/tengine/executor/../core/include -I/home/pi/tengine/executor/../include -I/home/pi/tengine/executor/../operator/include  -I/home/pi/tengine/executor/include   -Werror -DCONFIG_ARCH_ARM64=1 -I/home/pi/tengine/executor/operator/include -O3 -funroll-loops   -E sgemv_1x8_a72.S -o /home/pi/tengine/build/executor/operator/arm64/fc/sgemv_1x8_a72.s
gcc -std=gnu99  -g    -c /home/pi/tengine/build/executor/operator/arm64/fc/sgemv_1x8_a72.s -o /home/pi/tengine/build/executor/operator/arm64/fc/sgemv_1x8_a72.o
sgemv_1x8_a72.S: Assembler messages:
sgemv_1x8_a72.S:73: Error: ARM register expected -- `cmp x3,0x4'
sgemv_1x8_a72.S:74: Error: bad instruction `prfm pldl1keep,[x1,0x40]'
sgemv_1x8_a72.S:75: Error: bad instruction `prfm pldl1keep,[x2,0x200]'
sgemv_1x8_a72.S:76: Error: bad instruction `prfm pldl1keep,[x2,0x240]'
sgemv_1x8_a72.S:77: Error: bad instruction `movi d30,0'
sgemv_1x8_a72.S:78: Error: bad instruction `movi d31,0'
sgemv_1x8_a72.S:79: Error: selected processor does not support `cbz x0,start_convolution' in ARM mode
sgemv_1x8_a72.S:80: Error: bad instruction `ldp q30,q31,[x0]'
sgemv_1x8_a72.S:83: Error: ARM register expected -- `and x5,x3,0x3'
sgemv_1x8_a72.S:84: Error: unexpected character `l' in type specifier
sgemv_1x8_a72.S:84: Error: bad instruction `b.lt loop1'
sgemv_1x8_a72.S:85: Error: ARM register expected -- `lsr x6,x3,0x2'
sgemv_1x8_a72.S:90: Error: ARM register expected -- `ldr q0,[x1]'
sgemv_1x8_a72.S:91: Error: bad instruction `ldp q16,q17,[x2]'
sgemv_1x8_a72.S:92: Error: bad instruction `ldp q18,q19,[x2,0x20]'
sgemv_1x8_a72.S:93: Error: bad instruction `prfm pldl1keep,[x1,0x80]'
sgemv_1x8_a72.S:94: Error: ARM register expected -- `add x1,x1,0x10'
sgemv_1x8_a72.S:95: Error: ARM register expected -- `subs x6,x6,0x1'
sgemv_1x8_a72.S:97: Error: bad instruction `fmla v30.4s,v16.4s,v0.s[0]'
sgemv_1x8_a72.S:98: Error: bad instruction `fmla v31.4s,v17.4s,v0.s[0]'
sgemv_1x8_a72.S:99: Error: bad instruction `ldp q20,q21,[x2,0x40]'
sgemv_1x8_a72.S:100: Error: bad instruction `fmla v30.4s,v18.4s,v0.s[1]'
sgemv_1x8_a72.S:101: Error: bad instruction `prfm pldl1keep,[x2,0x400]'
sgemv_1x8_a72.S:102: Error: bad instruction `fmla v31.4s,v19.4s,v0.s[1]'
sgemv_1x8_a72.S:103: Error: bad instruction `ldp q22,q23,[x2,0x60]'
sgemv_1x8_a72.S:104: Error: bad instruction `fmla v30.4s,v20.4s,v0.s[2]'
sgemv_1x8_a72.S:105: Error: bad instruction `prfm pldl1keep,[x2,0x440]'
sgemv_1x8_a72.S:106: Error: ARM register expected -- `add x2,x2,0x80'
sgemv_1x8_a72.S:107: Error: bad instruction `fmla v31.4s,v21.4s,v0.s[2]'
sgemv_1x8_a72.S:108: Error: bad instruction `fmla v30.4s,v22.4s,v0.s[3]'
sgemv_1x8_a72.S:109: Error: bad instruction `fmla v31.4s,v23.4s,v0.s[3]'
sgemv_1x8_a72.S:111: Error: unexpected character `n' in type specifier
sgemv_1x8_a72.S:111: Error: bad instruction `b.ne loop4'
sgemv_1x8_a72.S:113: Error: selected processor does not support `cbz x5,save_result' in ARM mode
sgemv_1x8_a72.S:116: Error: ARM register expected -- `ldr s0,[x1],0x4'
sgemv_1x8_a72.S:117: Error: bad instruction `ldp q16,q17,[x2],0x20'

Did I use wrong compiler? 
thanks

**Comment by FengChueng** [comment]
have you solved it ?
