### ISSUE TITLE
[question] examples/tm_mobilenet_ssd.c  完整预处理流程是什么

### ISSUE THREAD

**Issue by tpoisonooo** [OAID/Tengine#848]
我理解所有的预处理都在`get_input_data` 里面

里面的流程依次是：

* `imread` 成 BGR
* `rgb2bgr_permute` 成 RGB
* `tengine_resize_f32` resize 到 300x300 
* `imread2caffe` 减均值，乘 scale

`imread2caffe` 的函数说明是，输入、输出均为 NCHW，不理解啥时候做的  HWC -> CHW 。

除非 `imread`读出来就已经是 CHW ？

**Comment by BUG1989** [comment]
请参考 `tm_yolov3.cpp` 直接使用 OpenCV 的 API 设计预处理。
