### ISSUE TITLE
mobilenet_ssd run time

### ISSUE THREAD

**Issue by vincent8877** [OAID/Tengine#85]
hi, thanks for the great work!

I make the example of mobilenet_ssd, and try to test the run time, but it seems the run time is instable and the function "get_input_data_ssd" cost too much time.

My paltform is firefly RK3399 and the stystem is ubuntu 16.04. I set the repeat time as 100 and test the run time in next 4 steps:

Step1: just the time of "set_tensor_buffer" and "run_graph"
<img width="518" alt="screenshot_2018-12-14_06-46-50" src="https://user-images.githubusercontent.com/40603468/50051561-d2ab5a00-014f-11e9-89cb-fef35071bf93.png">
<img width="290" alt="screenshot_2018-12-14_06-49-10" src="https://user-images.githubusercontent.com/40603468/50051566-e0f97600-014f-11e9-993a-31c12a9a19bc.png">
<img width="290" alt="screenshot_2018-12-14_06-50-14" src="https://user-images.githubusercontent.com/40603468/50051567-e3f46680-014f-11e9-95d8-e0d81d7a9e5e.png">
as you can see, the first 22 repeats, the run time is very stable, but after that run time becomes instable

Step2: add the function "get_input_data_ssd"
<img width="489" alt="screenshot_2018-12-14_06-54-15" src="https://user-images.githubusercontent.com/40603468/50051591-536a5600-0150-11e9-8141-29cba0967c60.png">
<img width="290" alt="screenshot_2018-12-14_06-54-39" src="https://user-images.githubusercontent.com/40603468/50051593-59603700-0150-11e9-9218-8b4bb8cdc52b.png">
<img width="292" alt="screenshot_2018-12-14_06-54-52" src="https://user-images.githubusercontent.com/40603468/50051594-5b29fa80-0150-11e9-8a06-efdeb96cb7ff.png">
the result looks alike as that of Step1, the first 11 repeats, time is stable and then instable, and after 100 repeats, the max_time and min_time varies a lot.
besides, compare to Step1 which avg_time is  158.798ms, the avg_time in Step2 is 232.255, means the function "get_input_data_ssd" takes 74ms per frame in average. I think this time is too long.

Step3: just the time of "get_input_data_ssd"
<img width="489" alt="screenshot_2018-12-14_06-56-26" src="https://user-images.githubusercontent.com/40603468/50051632-574aa800-0151-11e9-84eb-d62af4475483.png">
<img width="290" alt="screenshot_2018-12-14_06-57-02" src="https://user-images.githubusercontent.com/40603468/50051634-59ad0200-0151-11e9-81bb-55c3d733897b.png">
<img width="290" alt="screenshot_2018-12-14_06-57-16" src="https://user-images.githubusercontent.com/40603468/50051638-603b7980-0151-11e9-99d1-7b95c927866f.png">
as the results show: in 0 to 12 repeats and 27 to 44 repeats, the run time is stable and acceptable, but in other repeats the time is instable and too long.

Step4: try to make the time of "get_input_data_ssd" shorter
<img width="488" alt="screenshot_2018-12-14_06-59-31" src="https://user-images.githubusercontent.com/40603468/50051700-e8ba1a00-0151-11e9-8f3b-caed95da4644.png">
<img width="290" alt="screenshot_2018-12-14_07-11-30" src="https://user-images.githubusercontent.com/40603468/50051701-eb1c7400-0151-11e9-8b9b-b91d32ab7039.png">
<img width="292" alt="screenshot_2018-12-14_07-11-42" src="https://user-images.githubusercontent.com/40603468/50051704-efe12800-0151-11e9-931d-09d13b15e9c8.png">
in this Step, I modify the function  "get_input_data_ssd" ，just put the imread out of it, and test the time.
Although the result is still instable, the 0~2 repeats time seems very nice, and the avg_time (48.104ms) is shorter than that of Step3 (54.9964ms)

So here is my questions:
1. why the run time is instable, how can i do to make it stable?
2. the function "get_input_data_ssd" may take too long time i think, any suggestion to make it shorter?

Thank you.

**Comment by hey-yahei** [comment]
Hi, vincent8877
Thanks for your careful experiment.
1. I think you may forget to set mode of gpu as **perfomance** before test([Heterogeneous Computing#Step 2](https://github.com/OAID/Tengine/wiki/GPU-CPU%E5%BC%82%E6%9E%84%E8%B0%83%E5%BA%A6%E8%B7%91MobilenetSSD)). What's more, processors will reduce their working frequency automatically when they detect the rise of temperature. To make it work more stably, you can take some measures such as cooling fins and cooling fans to reduce the temperature.
2. I'm sorry that `get_input_data_ssd` function is not accelerated by Tengine. If you need to make it shorter, try to parallel it by using OpenMP, pThread and so on. Using other lighter vision library instead of OpenCV may be an another option.

**Comment by vincent8877** [comment]
thanks for reply @hey-yahei 
but actually i am not using GPU at the moment, i will try CPU/GPU running tomorrow
and the advices are instructive
thanks again

**Comment by renfeier** [comment]
> Hi, vincent8877
> Thanks for your careful experiment.
> 
> 1. I think you may forget to set mode of gpu as **perfomance** before test([Heterogeneous Computing#Step 2](https://github.com/OAID/Tengine/wiki/GPU-CPU%E5%BC%82%E6%9E%84%E8%B0%83%E5%BA%A6%E8%B7%91MobilenetSSD)). What's more, processors will reduce their working frequency automatically when they detect the rise of temperature. To make it work more stably, you can take some measures such as cooling fins and cooling fans to reduce the temperature.
> 2. I'm sorry that `get_input_data_ssd` function is not accelerated by Tengine. If you need to make it shorter, try to parallel it by using OpenMP, pThread and so on. Using other lighter vision library instead of OpenCV may be an another option.

so you think the reason of test time that instable  is the temperature?
