### ISSUE TITLE
Consider don't re-define `cpu_set_t` on Linux/Android

### ISSUE THREAD

**Issue by zchrissirhcz** [OAID/Tengine#863]
Hi, Tengine Team

There is `cpu_set_t` type, defined in Tengine's code:

https://github.com/OAID/Tengine/blob/041f6c160a686696cc73f4f2dcccf490b70950ca/source/system/cpu.c#L212

However, on Linux / Android platforms, there's also a system-wide `cpu_set_t` if we `#include <sched.h>`

And, there is already `#include <sched.h>` in Tengine's `cpu.c`:

https://github.com/OAID/Tengine/blob/041f6c160a686696cc73f4f2dcccf490b70950ca/source/system/cpu.c#L52

I would suggest remove the definition of `cpu_set_t`, or change name, or whatever. Otherwise, the two `cpu_set_t` makes both people & compiler confused.

**Comment by nihui** [comment]
因为在老版本ndk里面是没有定义cpu_set_t的。。
