### ISSUE TITLE
failed to set node ops for node: conv1-relu_conv1 op: Convolution

### ISSUE THREAD

**Issue by xfxty** [OAID/Tengine#87]
run common：./build/tests/bin/bench_sqz -r1，
tensor: prob created by node: prob is not consumed
add the node: prob into output list
Load model successfully
failed to set node ops for node: conv1-relu_conv1 op: Convolution
graph_task.cpp:229 failed to Prerun task on  dev executor: generic_probe
graph_task.cpp:321 bad status: CREATED
REPEAT COUNT= 1
graph_task.cpp:321 bad status: CREATED
Repeat [1] time 5.00 us per RUN. used 5 us
Segmentation fault (core dumped)

how to resolve it ,thanks

**Comment by hey-yahei** [comment]
Hi, xfxty
You run `./build/tests/bin/bench_sqz` but occur the error about **conv1_relu_conv1** node which is not in `./models/sqz.prototxt`. Have you modify the code in `./build/tests/bin/bench_sqz.cpp` and used another model?      
If so, which model did you use and what did you modify in `./build/tests/bin/bench_sqz.cpp`.

Thanks

**Comment by cyberfire** [comment]
It is probably no op implementation is built.
