### ISSUE TITLE
yolact  pytorch模型转onnx, 再转成tmfile, 预测时object检测正确, 但是分割的mask不对, 有遇到的吗?

### ISSUE THREAD

**Issue by jonado13** [OAID/Tengine#897]

**Comment by jonado13** [comment]
torch.onnx.export(net, 
                      inputs, 
                      output_onnx, 
                      verbose=True , #False, 
                      opset_version=10, #12, 
                      input_names=['input.1'], #image
                      output_names=['loc', 'conf', 'mask', 'proto'])

把opset_version版本改了一下就可以了, 之前是12,现在改成10就正常了

**Comment by BUG1989** [comment]
@jonado13 谢谢您的解答
