### ISSUE TITLE
yolox-nano模型转到tmfile之后精度下降的相关问题

### ISSUE THREAD

**Issue by FeiGeChuanShu** [OAID/Tengine#898]
按照虫叔的教程，把yolox-nano模型转到了tengine，使用最新的tengine-lite-v1.4，但是测试过程中发现：
1、如果打开fuse hardswish精度就会损失很多；
2、使用sigmoid+mul结构，精度会有所好转，但是跟ncnn相比较还是有一定精度下降。
特此附上onnx和tmfile模型，请大佬指点！
https://pan.baidu.com/s/15tDdcV4ZKGU2xuVekZhTyw 提取码: hpsr

**Comment by BUG1989** [comment]
好的，问题不大，下午帮你看看

**Comment by FeiGeChuanShu** [comment]
1、原始激活是swish，tengine为了适配A311D npu的hardswish，才在yolov5s脚本里加了sigmoid+mul替换为hardswish，其他平台不建议使用此操作。
2、由于测试时版本是v1.4，验证是版本问题，更新到最新版本精度下降问题解决。
多谢虫叔帮忙调试：）
