### ISSUE TITLE
yolox-tiny和yolox-s按照hardswish激活精度尚可，求白嫖VIM3 NPU方案

### ISSUE THREAD

**Issue by FeiGeChuanShu** [OAID/Tengine#904]
如题，之前试过 yolox-nano 的 hardswish 莫模型，精度掉的厉害，后尝试 yolox-tiny 和 yolox-s 的 hardswish 模型，精度可以满足要求，求白嫖 VIM3 NPU 的方案 ，附上模型文件
https://pan.baidu.com/s/15tDdcV4ZKGU2xuVekZhTyw 提取码: hpsr

**Comment by BUG1989** [comment]
@FeiGeChuanShu 好的，马上安排上。

**Comment by FeiGeChuanShu** [comment]
Tengine 支持 NPU 模型部署-YOLOX 
https://zhuanlan.zhihu.com/p/392387835
废话不多说 我要去白嫖了
