### ISSUE TITLE
Does Tengine support Int8 on rk3288 or rk3399 now? If so, how to use it?

### ISSUE THREAD

**Issue by ZGAI** [OAID/Tengine#95]
Does Tengine support Int8 on rk3288 or rk3399 now? If so, how to use it? I have not found any document about it, but I found a picture said it support INT8.

**Comment by gaojinwei01** [comment]
Hi，

Tengine does support INT8 inferencing on Arm boards, but the code is not open sourced yet. Instead we provide prebuild Tengine library supporting int8 inferencing for developer. We already publish raspberry version last week and will publish rk3399 and rk3288 version soon.
Please contact developer@openailab.com for accessing the developer version.

Best regards,
Xiaowei
