### ISSUE TITLE
memory leak on mtcnn example

### ISSUE THREAD

**Issue by ohnosang** [OAID/Tengine#96]
in runPnet runRnet runOnet 
好几个输出层的tensor对象都没有用put_graph_tensor释放掉，
比如conv4-2  prob1 这两个只在最后用put_graph_tensor释放掉prob1的tensor 所以造成了内存泄露

**Comment by gaojinwei01** [comment]
Hi,

You are using the old version MTCNN example code.
Please update your example code to Tengine 1.0 version and the issue will be resolved.

Best regards,
Xiaowei
