### ISSUE TITLE
How can I get the error reason of run_graph

### ISSUE THREAD

**Issue by liyuming1978** [OAID/Tengine#97]
hi all:
      I have built the android lib , and replace it in Tengine-app, but the run_graph always return false, I use the prebuild lib too (it seems the prebuild lib has updated) , the same fails.
     so is there any error reason function to use to get the detail failure reason for run_graph?  not only true or false.

**Comment by cyberfire** [comment]
@liyuming1978 

You can use get_tengine_errno() to have a try.  As the procedure of run_graph is complicated, if that errno cannot provide useful hints,  please try gdb. 

Thanks,

Haitao
