### ISSUE TITLE
Tools Failed on khadas vim3

### ISSUE THREAD

**Issue by lovehuanhuan** [OAID/Tengine#973]
Welcome to Fenix 1.0.5 Ubuntu 20.04.2 LTS Linux 4.9.241  
 _  ___               _            __     _____ __  __ _____ 
| |/ / |__   __ _  __| | __ _ ___  \ \   / /_ _|  \/  |___ / 
| ' /| '_ \ / _` |/ _` |/ _` / __|  \ \ / / | || |\/| | |_ \ 
| . \| | | | (_| | (_| | (_| \__ \   \ V /  | || |  | |___) |
|_|\_\_| |_|\__,_|\__,_|\__,_|___/    \_/  |___|_|  |_|____/ 
                                                             

 * Website:        https://www.khadas.com
 * Documentation:  https://docs.khadas.com
 * Forum:          https://forum.khadas.com

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

khadas@Khadas:~$ cd Desktop/
khadas@Khadas:~/Desktop$ sudo mkdir zzp
[sudo] password for khadas: 
khadas@Khadas:~/Desktop$ sudo chmod 777 zzp/
khadas@Khadas:~/Desktop$ cd zzp/
khadas@Khadas:~/Desktop/zzp$ ls
quant_tool_uint8
khadas@Khadas:~/Desktop/zzp$ sudo chmod 777 *
khadas@Khadas:~/Desktop/zzp$ sudo ./quant_tool_uint8 
./quant_tool_uint8: 1: ELF: not found
./quant_tool_uint8: 6: Syntax error: word unexpected (expecting ")")
khadas@Khadas:~/Desktop/zzp$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

khadas@Khadas:~/Desktop/zzp$ sudo chmod 777 convert_tool 
khadas@Khadas:~/Desktop/zzp$ sudo ./convert_tool 
./convert_tool: 1: ELF: not found
./convert_tool: 2: Syntax error: "(" unexpected
khadas@Khadas:~/Desktop/zzp$

**Comment by BUG1989** [comment]
模型转换工具，在 x86 的 PC 上编译运行即可。
