### ISSUE TITLE
find bug in graph_executor.cpp

### ISSUE THREAD

**Issue by feiliuzhixia1000m** [OAID/Tengine#98]
in line 138:
if(layout == TENGINE_LAYOUT_NCHW || layout == TENGINE_LAYOUT_NCHW)

I think it should be:
 if(layout == TENGINE_LAYOUT_NCHW || layout == TENGINE_LAYOUT_NHWC)

thanks

**Comment by cyberfire** [comment]
@feiliuzhixia1000m 

Yes. You are totally correct.  

Thanks for reviewing and reporting this bug.

-Haitao
