### ISSUE TITLE
[Question] Model Zoo - Baidu

### ISSUE THREAD

**Issue by eymengunay** [OAID/Tengine#99]
Hello,

I recently stumbled upon this project and wanted to give it a try. However I realized that pretrained models are currently hosted on baidu which seems to ask for a Chinese mobile number to create an account.

Do you have any suggestions regarding how to download models?

Thank you!

**Comment by vincent8877** [comment]
which model you want?
i can send to you by e-mail

**Comment by eymengunay** [comment]
I'm mostly interested in testing the mobilenet_ssd implementation.

Thank you, I appreciate it!

**Comment by oanhrung** [comment]
@vincent8877 I also need the model mobilenet_ssd but I cannot download it. Can you send them to me by email? Thanks

**Comment by eymengunay** [comment]
Hello @oanhrung ,

I can forward you the mail but unfortunately I can't see an email address on your profile.

**Comment by Heimerdinger** [comment]
Hello @eymengunay ,
I also need the model to verify it. May you send them file to me by email? Many Thanks.

**Comment by eymengunay** [comment]
Hello @Heimerdinger ,

I have just forwarded you the email.

**Comment by Heimerdinger** [comment]
Hello @eymengunay ,
I receive it by mail. Very Thanks for your help.

**Comment by pitchaya** [comment]
Would anyone be able to forward me mobilenet_ssd as well?  
   Thank you very much

**Comment by eymengunay** [comment]
@pitchaya: You don't seem to have an email address on your profile (or it is not publicly visible)

**Comment by Adhithya-tech** [comment]
@eymengunay  Could you forward mobilenet.tmfile to my email?

**Comment by eymengunay** [comment]
Hello @Adhithya-tech,
I could but you have no information whatsoever on your profile. I have no clue what your email address is.

This is the third time that the same thing is happening. For the future if somebody needs the file please at least make sure that you have an email address on your profile.

**Comment by KrishnaShalini0518-arch** [comment]
Hello @eymengunay ,
I tried accessing tengine models through .deb file. But didn't find any.
Kindly share mobilenet_ssd.tmfile, retinaface.tmfile, yolact.tmfile to my email.

**Comment by leeje2993** [comment]
Hello @eymengunay ,
Would you forward me mobilenet_ssd and darknet_yolo to my email?
Thank you in advance

**Comment by eymengunay** [comment]
Hello @leeje2993,

Unfortunately I only have the mobilenet_ssd model which I just sent it to you.

**Comment by KrishnaShalini0518-arch** [comment]
Hi @eymengunay ,

Can you share the mobilenet_ssd model to my email? Thank you very much.

**Comment by eymengunay** [comment]
Oh hello @KrishnaShalini0518-arch,

I guess I overlooked your message and saw only the last one from @leeje2993. I have now forwarded it to you too.
